/**
 * CEFR Level Final Exams - Separate from regular lessons
 * Level 1 only for MVP - Final exam with 20 comprehensive questions
 */
const level1FinalExam = {
    levelId: 1,
    title: 'Level 1 – Final Exam',
    description: 'Final examination covering all Level 1 content',
    content: {
        introduction: 'Welcome to your Level 1 Final Exam! This comprehensive exam tests your knowledge across all topics covered in Level 1, including the alphabet, greetings, numbers, colors, classroom objects, and pronouns.',
        objectives: [
            'Demonstrate mastery of all Level 1 content (alphabet, greetings, numbers)',
            'Apply knowledge of colors, classroom objects, and pronouns',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 2',
            'Evaluate overall English learning progress',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 1 materials. You will be tested on letters, greetings, numbers, colors, objects, and pronouns. Do your best and show everything you have learned!',
        summary: 'You have completed the Level 1 Final Exam. This comprehensive assessment evaluates all your learning from Level 1 and prepares you for advancement.',
    },
    exercises: [
        {
            type: 'multiple-choice',
            question: 'What is the small (lowercase) version of the letter "H"?',
            options: ['b', 'n', 'h', 'm'],
            correctAnswers: [2],
            explanation: 'The lowercase version of "H" is "h".',
        },
        {
            type: 'multiple-choice',
            question: 'Which letter comes immediately before "Z"?',
            options: ['W', 'X', 'Y', 'V'],
            correctAnswers: [2],
            explanation: 'The letter Y comes immediately before Z.',
        },
        {
            type: 'multiple-choice',
            question: 'What is the first letter of the English alphabet?',
            options: ['A', 'B', 'Z', 'M'],
            correctAnswers: [0],
            explanation: 'A is the first letter of the English alphabet.',
        },
        {
            type: 'multiple-choice',
            question: 'Which sequence shows the correct order of letters?',
            options: ['X Z Y', 'X Y Z', 'Z Y X', 'Y X Z'],
            correctAnswers: [1],
            explanation: 'X, Y, Z is the correct alphabetical order.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you say to someone when you see them in the morning?',
            options: ['Good night', 'Good morning', 'Goodbye', 'See you later'],
            correctAnswers: [1],
            explanation: '"Good morning" is the correct greeting when you see someone in the morning.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you say when you leave?',
            options: ['Hello', 'Welcome', 'Goodbye', 'Please'],
            correctAnswers: [2],
            explanation: '"Goodbye" is what you say when you leave.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you say when you go to sleep?',
            options: ['Good morning', 'Good afternoon', 'Good night', 'Hello'],
            correctAnswers: [2],
            explanation: '"Good night" is what you say when you go to sleep.',
        },
        {
            type: 'multiple-choice',
            question: 'How do you spell the number "2"?',
            options: ['Too', 'Two', 'Tow', 'Tu'],
            correctAnswers: [1],
            explanation: 'The correct spelling of the number 2 is "Two".',
        },
        {
            type: 'multiple-choice',
            question: 'Which number comes right after 4?',
            options: ['3', '5', '6', '2'],
            correctAnswers: [1],
            explanation: 'The number 5 comes right after 4.',
        },
        {
            type: 'listening',
            question: 'Listen and select the number you hear:',
            audioPrompt: '3',
            options: ['1', '2', '3', '4'],
            correctAnswers: [2],
            explanation: 'You heard the number 3 (three).',
        },
        {
            type: 'multiple-choice',
            question: 'Which number comes right after 6?',
            options: ['5', '7', '8', '9'],
            correctAnswers: [1],
            explanation: 'The number 7 comes right after 6.',
        },
        {
            type: 'multiple-choice',
            question: 'How do you spell the number "10"?',
            options: ['Tin', 'Ten', 'Tan', 'Ton'],
            correctAnswers: [1],
            explanation: 'The correct spelling of the number 10 is "Ten".',
        },
        {
            type: 'multiple-choice',
            question: 'What color is the sun?',
            options: ['Black', 'White', 'Yellow', 'Blue'],
            correctAnswers: [2],
            explanation: 'The sun is yellow.',
        },
        {
            type: 'multiple-choice',
            question: 'What color is an apple or a strawberry?',
            options: ['Blue', 'Red', 'Green', 'Yellow'],
            correctAnswers: [1],
            explanation: 'Apples and strawberries are typically red.',
        },
        {
            type: 'multiple-choice',
            question: 'How do you spell the color of grass?',
            options: ['Grene', 'Green', 'Grin', 'Gren'],
            correctAnswers: [1],
            explanation: 'The correct spelling of the color of grass is "Green".',
        },
        {
            type: 'multiple-choice',
            question: 'What do you use to write on paper?',
            options: ['A book', 'A pen', 'A chair', 'A desk'],
            correctAnswers: [1],
            explanation: 'You use a pen to write on paper.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you open to read?',
            options: ['A bag', 'A desk', 'A book', 'A pen'],
            correctAnswers: [2],
            explanation: 'You open a book to read.',
        },
        {
            type: 'multiple-choice',
            question: 'Which word do you use to talk about a boy?',
            options: ['She', 'I', 'You', 'He'],
            correctAnswers: [3],
            explanation: '"He" is the pronoun you use to talk about a boy.',
        },
        {
            type: 'multiple-choice',
            question: 'Which word do you use to talk about a girl?',
            options: ['He', 'I', 'She', 'You'],
            correctAnswers: [2],
            explanation: '"She" is the pronoun you use to talk about a girl.',
        },
        {
            type: 'multiple-choice',
            question: 'Which word do you use to talk about yourself?',
            options: ['You', 'He', 'I', 'She'],
            correctAnswers: [2],
            explanation: '"I" is the pronoun you use to talk about yourself.',
        },
    ],
    audioContent: [
        { text: 'Good morning', type: 'phrase', context: 'Morning greeting for final exam' },
        { text: '3', type: 'word', context: 'Number three' },
        { text: 'Green', type: 'word', context: 'Color green' },
    ],
};
const level2FinalExam = {
    levelId: 2,
    title: 'Level 2 – Final Exam',
    description: 'Final examination covering all Level 2 content',
    content: {
        introduction: 'Welcome to your Level 2 Final Exam! This comprehensive exam tests your knowledge across all topics covered in Level 2, including personal information, family members, everyday objects, time and days, food and drink, daily activities, simple adjectives, and places in a town.',
        objectives: [
            'Demonstrate mastery of all Level 2 content',
            'Apply knowledge of personal information and family vocabulary',
            'Show understanding of daily routines and common places',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 3',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 2 materials. You will be tested on greetings, family members, objects, days of the week, food and drink, activities, adjectives, and places. Do your best!',
        summary: 'You have completed the Level 2 Final Exam. This comprehensive assessment evaluates all your learning from Level 2.',
    },
    exercises: [
        {
            type: 'multiple-choice',
            question: 'What do you say when you meet someone for the first time?',
            options: ['Nice to meet you.', 'Goodbye.', 'Thank you.', 'Excuse me.'],
            correctAnswers: [0],
            explanation: '"Nice to meet you." is the correct greeting when meeting someone for the first time.',
        },
        {
            type: 'multiple-choice',
            question: 'My father\'s sister is my _______.',
            options: ['aunt', 'uncle', 'sister', 'mother'],
            correctAnswers: [0],
            explanation: 'Your father\'s sister is your aunt.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you use to open a locked door?',
            options: ['A key', 'A watch', 'A wallet', 'A window'],
            correctAnswers: [0],
            explanation: 'You use a key to open a locked door.',
        },
        {
            type: 'multiple-choice',
            question: 'Which day comes after Monday?',
            options: ['Wednesday', 'Sunday', 'Tuesday', 'Friday'],
            correctAnswers: [2],
            explanation: 'Tuesday comes after Monday.',
        },
        {
            type: 'listening',
            question: 'Listen and select the word you hear:',
            audioPrompt: 'Breakfast',
            options: ['Lunch', 'Dinner', 'Breakfast', 'Food'],
            correctAnswers: [2],
            explanation: 'You heard the word "Breakfast".',
        },
        {
            type: 'multiple-choice',
            question: 'What do many people drink hot in the morning?',
            options: ['Coffee', 'Water', 'Juice', 'Ice'],
            correctAnswers: [0],
            explanation: 'Many people drink coffee hot in the morning.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you do at night in your bed?',
            options: ['Sleep', 'Cook', 'Work', 'Study'],
            correctAnswers: [0],
            explanation: 'You sleep in your bed at night.',
        },
        {
            type: 'multiple-choice',
            question: 'What is the opposite of "hot"?',
            options: ['Cold', 'Warm', 'Big', 'New'],
            correctAnswers: [0],
            explanation: 'Cold is the opposite of hot.',
        },
        {
            type: 'multiple-choice',
            question: 'Where do you go to buy food and groceries?',
            options: ['The supermarket', 'The park', 'The hospital', 'The cinema'],
            correctAnswers: [0],
            explanation: 'You go to the supermarket to buy food and groceries.',
        },
        {
            type: 'listening',
            question: 'Listen to the sentence: "He is a doctor." What is his job?',
            audioPrompt: 'He is a doctor',
            options: ['Teacher', 'Doctor', 'Driver', 'Student'],
            correctAnswers: [1],
            explanation: 'He is a doctor.',
        },
        {
            type: 'multiple-choice',
            question: 'Where are you from?',
            options: ['I am from Spain.', 'I am 20 years old.', 'My name is John.', 'I am fine.'],
            correctAnswers: [0],
            explanation: 'This is a correct way to answer where you are from.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "This is _______ brother. His name is Paul."',
            options: ['my', 'he', 'she', 'me'],
            correctAnswers: [0],
            explanation: '"my" is the correct possessive pronoun.',
        },
        {
            type: 'multiple-choice',
            question: 'You use a _______ to call people and check the internet.',
            options: ['smartphone', 'television', 'clock', 'notebook'],
            correctAnswers: [0],
            explanation: 'You use a smartphone to call people and check the internet.',
        },
        {
            type: 'multiple-choice',
            question: 'How many days are in one week?',
            options: ['7', '5', '12', '30'],
            correctAnswers: [0],
            explanation: 'There are 7 days in one week.',
        },
        {
            type: 'listening',
            question: 'Listen and select the number you hear:',
            audioPrompt: 'Twelve',
            options: ['2', '20', '12', '7'],
            correctAnswers: [2],
            explanation: 'You heard the number "Twelve" (12).',
        },
        {
            type: 'multiple-choice',
            question: 'Which word is a drink?',
            options: ['Water', 'Rice', 'Chicken', 'Cheese'],
            correctAnswers: [0],
            explanation: 'Water is a drink.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "He _______ to the office by train."',
            options: ['goes', 'go', 'going', 'went'],
            correctAnswers: [0],
            explanation: '"goes" is the correct verb form.',
        },
        {
            type: 'multiple-choice',
            question: 'An elephant is large, but a mouse is _______.',
            options: ['small', 'tall', 'fast', 'heavy'],
            correctAnswers: [0],
            explanation: 'A mouse is small compared to an elephant.',
        },
        {
            type: 'multiple-choice',
            question: 'Where do children go to learn?',
            options: ['A school', 'A bank', 'A restaurant', 'A hotel'],
            correctAnswers: [0],
            explanation: 'Children go to school to learn.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "This book is not cheap. It is _______."',
            options: ['expensive', 'free', 'easy', 'old'],
            correctAnswers: [0],
            explanation: '"expensive" is the correct opposite of cheap.',
        },
    ],
};
const level3FinalExam = {
    levelId: 3,
    title: 'Level 3 – Final Exam',
    description: 'Final examination covering all Level 3 content',
    content: {
        introduction: 'Welcome to your Level 3 Final Exam! This comprehensive exam tests your knowledge across all topics covered in Level 3, including free time activities, house and rooms, weather and seasons, past events, health and body, clothes and shopping, transport and travel, and making plans.',
        objectives: [
            'Demonstrate mastery of all Level 3 content',
            'Apply knowledge of activities, places, and weather vocabulary',
            'Show understanding of past tense and future plans',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 4',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 3 materials. You will be tested on activities, rooms, weather, past events, body parts, clothes, transport, and plans. Do your best!',
        summary: 'You have completed the Level 3 Final Exam. This comprehensive assessment evaluates all your learning from Level 3.',
    },
    exercises: [
        {
            type: 'multiple-choice',
            question: 'What do you need if you want to play tennis?',
            options: ['A racket and a ball', 'A book and a pen', 'A bicycle and a helmet', 'A guitar and a piano'],
            correctAnswers: [0],
            explanation: 'You need a racket and a ball to play tennis.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "I really enjoy _______ photos of nature."',
            options: ['take', 'taking', 'took', 'taken'],
            correctAnswers: [1],
            explanation: '"taking" is the correct gerund form.',
        },
        {
            type: 'multiple-choice',
            question: 'Where do you usually cook food in a house?',
            options: ['In the bedroom', 'In the kitchen', 'In the bathroom', 'In the garage'],
            correctAnswers: [1],
            explanation: 'You usually cook food in the kitchen.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "The keys are _______ the kitchen table."',
            options: ['in', 'on', 'underneath of', 'between'],
            correctAnswers: [1],
            explanation: '"on" is the correct preposition for something on top of a table.',
        },
        {
            type: 'listening',
            question: 'Listen and select the word you hear:',
            audioPrompt: 'Umbrella',
            options: ['Raincoat', 'Sunglasses', 'Umbrella', 'Boots'],
            correctAnswers: [2],
            explanation: 'You heard the word "Umbrella".',
        },
        {
            type: 'multiple-choice',
            question: 'Which season is usually the coldest?',
            options: ['Summer', 'Spring', 'Winter', 'Autumn'],
            correctAnswers: [2],
            explanation: 'Winter is usually the coldest season.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Yesterday, I _______ to the supermarket and bought some fruit."',
            options: ['go', 'went', 'going', 'goes'],
            correctAnswers: [1],
            explanation: '"went" is the correct past tense form.',
        },
        {
            type: 'multiple-choice',
            question: 'What is the past tense of the verb "watch"?',
            options: ['Watchy', 'Watching', 'Watched', 'Wrote'],
            correctAnswers: [2],
            explanation: '"Watched" is the correct past tense of "watch".',
        },
        {
            type: 'listening',
            question: 'Listen to the phrase and select what you hear:',
            audioPrompt: 'I have a headache',
            options: ['I have a stomach ache.', 'I have a headache.', 'I have a toothache.', 'I feel great today.'],
            correctAnswers: [1],
            explanation: 'You heard "I have a headache."',
        },
        {
            type: 'multiple-choice',
            question: 'Which part of the body connects your foot to your leg?',
            options: ['The ankle', 'The elbow', 'The finger', 'The shoulder'],
            correctAnswers: [0],
            explanation: 'The ankle connects your foot to your leg.',
        },
        {
            type: 'multiple-choice',
            question: 'What do you wear around your neck when it is freezing in winter?',
            options: ['A scarf', 'A belt', 'Socks', 'A ring'],
            correctAnswers: [0],
            explanation: 'You wear a scarf around your neck in winter.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Excuse me, how _______ is this blue jacket?"',
            options: ['much', 'many', 'cost', 'price'],
            correctAnswers: [0],
            explanation: '"much" is the correct quantifier for price.',
        },
        {
            type: 'multiple-choice',
            question: 'How do you go across the ocean to another continent?',
            options: ['By airplane', 'By bicycle', 'By train', 'By walking'],
            correctAnswers: [0],
            explanation: 'You go by airplane across the ocean.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "We need to buy a _______ before we get on the bus."',
            options: ['ticket', 'passport', 'map', 'suitcase'],
            correctAnswers: [0],
            explanation: 'You need to buy a ticket to get on the bus.',
        },
        {
            type: 'listening',
            question: 'Listen to the sentence: "We are going to visit London next week." What is the plan?',
            audioPrompt: 'We are going to visit London next week',
            options: ['To move to London', 'To visit London', 'To leave London', 'To work in London'],
            correctAnswers: [1],
            explanation: 'The plan is to visit London.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Tomorrow, I am going to _______ my grandparents."',
            options: ['visit', 'visiting', 'visited', 'visits'],
            correctAnswers: [0],
            explanation: '"visit" is the correct infinitive form.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "There _______ three chairs in the dining room."',
            options: ['is', 'am', 'are', 'be'],
            correctAnswers: [2],
            explanation: '"are" is the correct verb form for plural "chairs".',
        },
        {
            type: 'multiple-choice',
            question: 'What is the weather like when you cannot see far because of a white cloud near the ground?',
            options: ['Foggy', 'Sunny', 'Windy', 'Dry'],
            correctAnswers: [0],
            explanation: 'That weather condition is called foggy.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Did you _______ the English homework yesterday?"',
            options: ['finish', 'finished', 'finishing', 'finishes'],
            correctAnswers: [0],
            explanation: '"finish" is the correct infinitive form.',
        },
        {
            type: 'multiple-choice',
            question: 'Where do airplanes land and take off?',
            options: ['At the airport', 'At the station', 'At the port', 'At the garage'],
            correctAnswers: [0],
            explanation: 'Airplanes land and take off at the airport.',
        },
    ],
};
const level4FinalExam = {
    levelId: 4,
    title: 'Level 4 – Final Exam',
    description: 'Final examination covering all Level 4 content',
    content: {
        introduction: 'Welcome to your Level 4 Final Exam! This comprehensive exam tests your knowledge across all topics covered in Level 4, including comparative adjectives, experiences (present perfect), work and careers, modals of ability and obligation, technology and media, life events, superlative adjectives, and appearance and personality.',
        objectives: [
            'Demonstrate mastery of all Level 4 content',
            'Apply knowledge of comparatives and superlatives',
            'Show understanding of present perfect tense',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 5',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 4 materials. You will be tested on comparisons, experiences, careers, modals, technology, life events, superlatives, and personality. Do your best!',
        summary: 'You have completed the Level 4 Final Exam. This comprehensive assessment evaluates all your learning from Level 4.',
    },
    exercises: [
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "My new phone is _______ than my old one."',
            options: ['faster', 'fast', 'more fast', 'fastest'],
            correctAnswers: [0],
            explanation: '"faster" is the correct comparative form.',
        },
        {
            type: 'multiple-choice',
            question: 'A Ferrari is _______ than a regular bicycle.',
            options: ['more expensive', 'expensiveer', 'most expensive', 'as expensive'],
            correctAnswers: [0],
            explanation: '"more expensive" is the correct comparative form.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Have you ever _______ sushi before?"',
            options: ['eat', 'ate', 'eaten', 'eating'],
            correctAnswers: [2],
            explanation: '"eaten" is the correct past participle for present perfect.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "I have _______ to Paris twice in my life."',
            options: ['been', 'went', 'go', 'gone'],
            correctAnswers: [0],
            explanation: '"been" is the correct form with "have".',
        },
        {
            type: 'listening',
            question: 'Listen and select the word you hear:',
            audioPrompt: 'Architect',
            options: ['Engineer', 'Architect', 'Builder', 'Doctor'],
            correctAnswers: [1],
            explanation: 'You heard the word "Architect".',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "She works in a hospital. She is a _______."',
            options: ['nurse', 'teacher', 'lawyer', 'shop assistant'],
            correctAnswers: [0],
            explanation: 'A person who works in a hospital is a nurse.',
        },
        {
            type: 'multiple-choice',
            question: 'You _______ wear a seatbelt while driving a car. It is the law.',
            options: ['must', 'should', 'can', 'might'],
            correctAnswers: [0],
            explanation: '"must" expresses an obligation or legal requirement.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "When I was five years old, I _______ swim, but now I can."',
            options: ['could not', 'cannot', 'should not', 'must not'],
            correctAnswers: [0],
            explanation: '"could not" is the correct past form of "cannot".',
        },
        {
            type: 'listening',
            question: 'Listen to the phrase and select what you hear:',
            audioPrompt: 'Download the file',
            options: ['Delete the file.', 'Download the file.', 'Upload the file.', 'Share the file.'],
            correctAnswers: [1],
            explanation: 'You heard "Download the file."',
        },
        {
            type: 'multiple-choice',
            question: 'What part of a computer or smartphone shows you the images and text?',
            options: ['The screen', 'The keyboard', 'The mouse', 'The speaker'],
            correctAnswers: [0],
            explanation: 'The screen shows you the images and text.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "My brother _______ from university last summer."',
            options: ['graduated', 'born', 'married', 'grew up'],
            correctAnswers: [0],
            explanation: '"graduated" is the correct past tense.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "We decided to _______ house because we needed more space."',
            options: ['move', 'change', 'leave', 'stay'],
            correctAnswers: [0],
            explanation: '"move" means to change residence.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "Mount Everest is the _______ mountain in the world."',
            options: ['highest', 'higher', 'most high', 'highestly'],
            correctAnswers: [0],
            explanation: '"highest" is the correct superlative form.',
        },
        {
            type: 'multiple-choice',
            question: 'Which city is the _______ expensive city to live in?',
            options: ['most', 'more', 'much', 'very'],
            correctAnswers: [0],
            explanation: '"most" forms the superlative for "expensive".',
        },
        {
            type: 'listening',
            question: 'Listen to the sentence: "He has curly hair." What does his hair look like?',
            audioPrompt: 'He has curly hair',
            options: ['It is straight.', 'It forms loops and circles.', 'He has no hair.', 'It is very long.'],
            correctAnswers: [1],
            explanation: 'Curly hair forms loops and circles.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "He is very _______. He always shares his things with others."',
            options: ['generous', 'selfish', 'lazy', 'shy'],
            correctAnswers: [0],
            explanation: '"generous" means willing to share.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "The weather today is _______ than it was yesterday."',
            options: ['better', 'gooder', 'best', 'more good'],
            correctAnswers: [0],
            explanation: '"better" is the correct irregular comparative.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "She _______ never seen a whale in the ocean."',
            options: ['has', 'have', 'is', 'did'],
            correctAnswers: [0],
            explanation: '"has" is the correct present perfect auxiliary.',
        },
        {
            type: 'multiple-choice',
            question: 'Complete the sentence: "If you feel sick, you _______ stay at home and rest."',
            options: ['should', 'must to', 'can to', 'could to'],
            correctAnswers: [0],
            explanation: '"should" expresses a recommendation.',
        },
        {
            type: 'multiple-choice',
            question: 'That was the _______ movie I have ever seen! It was terrible.',
            options: ['worst', 'badest', 'worse', 'most bad'],
            correctAnswers: [0],
            explanation: '"worst" is the correct superlative of "bad".',
        },
    ],
};
const level5FinalExam = {
    levelId: 5,
    title: 'Level 5 – Final Exam',
    description: 'Final examination covering all Level 5 content',
    content: {
        introduction: 'Welcome to your Level 5 Final Exam! This comprehensive exam tests your knowledge covering reported speech, conditional statements, phrasal verbs, complex sentences, future plans, opinions and arguments, storytelling, and problem solving.',
        objectives: [
            'Demonstrate mastery of all Level 5 content',
            'Apply knowledge of reported speech and conditionals',
            'Show understanding of phrasal verbs and complex sentences',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 6',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 5 materials. You will be tested on reported speech, conditionals, phrasal verbs, complex sentences, future plans, opinions, storytelling, and problem solving. Do your best!',
        summary: 'You have completed the Level 5 Final Exam. This comprehensive assessment evaluates all your learning from Level 5.',
    },
    exercises: [
        { type: 'multiple-choice', question: 'Convert to reported: "I am tired." → "He said he _______."', options: ['was tired', 'is tired', 'am tired', 'been tired'], correctAnswers: [0], explanation: 'Present becomes past in reported speech.' },
        { type: 'multiple-choice', question: 'Complete first conditional: "If you study hard, you _______ pass."', options: ['will', 'would', 'can', 'might'], correctAnswers: [0], explanation: 'First conditional uses will for likely future.' },
        { type: 'listening', question: 'What does "give up" mean?', audioPrompt: 'stop or quit', options: ['start', 'stop or quit', 'share', 'donate'], correctAnswers: [1], explanation: '"Give up" means to quit or stop.' },
        { type: 'multiple-choice', question: 'Complete: "_______ he was tired, he continued working."', options: ['Because', 'Although', 'If', 'When'], correctAnswers: [1], explanation: '"Although" shows contrast.' },
        { type: 'listening', question: 'Complete: "I _______ study medicine."', audioPrompt: 'am going to', options: ['will', 'am going to', 'go', 'am'], correctAnswers: [1], explanation: '"Going to" expresses a decided plan.' },
        { type: 'multiple-choice', question: 'How do you state an opinion?', options: ['You are wrong', 'In my opinion', 'Everyone knows', 'Obviously'], correctAnswers: [1], explanation: '"In my opinion" is polite.' },
        { type: 'multiple-choice', question: 'Which sequence word starts a narrative?', options: ['Then', 'Once', 'Finally', 'After'], correctAnswers: [1], explanation: '"Once" sets the initial scene.' },
        { type: 'listening', question: 'Complete problem statement: "The issue is that _______."', audioPrompt: 'we need more information', options: ['nobody knows', 'we need more information', 'it is easy', 'it is solved'], correctAnswers: [1], explanation: 'Clear problem statements specify the issue.' },
        { type: 'multiple-choice', question: 'Complete second conditional: "If I were rich, I _______ travel."', options: ['will', 'would', 'am', 'can'], correctAnswers: [1], explanation: '"Would" for hypothetical situations.' },
        { type: 'listening', question: 'Convert: "Do you like pizza?" → "She asked if I _______."', audioPrompt: 'liked', options: ['like', 'liked', 'likes', 'would like'], correctAnswers: [1], explanation: 'Questions use past in reported speech.' },
        { type: 'multiple-choice', question: 'Complete: "I need to _______ my younger siblings."', options: ['look at', 'look after', 'look for', 'look up'], correctAnswers: [1], explanation: '"Look after" means care for.' },
        { type: 'multiple-choice', question: 'Complete: "Unless you finish homework, you _______not watch TV."', options: ['will', 'would', 'can', 'are'], correctAnswers: [0], explanation: '"Unless" works like first conditional.' },
        { type: 'listening', question: 'Complete: "Eventually, I _______ it was a mistake."', audioPrompt: 'realized', options: ['realize', 'realized', 'am realizing', 'have realized'], correctAnswers: [1], explanation: 'Past simple for narrative endings.' },
        { type: 'multiple-choice', question: 'How do you evaluate a solution?', options: ['That won\'t work', 'That solution might work, but...', 'Never', 'It is stupid'], correctAnswers: [1], explanation: 'Respectfully evaluate while considering factors.' },
        { type: 'multiple-choice', question: 'Complete: "She _______ smoking three months ago."', options: ['gave in', 'gave out', 'gave up', 'gave back'], correctAnswers: [2], explanation: '"Give up" means to quit.' },
        { type: 'multiple-choice', question: 'Complete: "While I _______ home, I saw a bird."', options: ['walked', 'was walking', 'walk', 'have walked'], correctAnswers: [1], explanation: 'Past continuous shows interrupted action.' },
        { type: 'listening', question: 'Complete: "I _______ that climate change is real."', audioPrompt: 'believe', options: ['argue', 'believe', 'claim', 'say'], correctAnswers: [1], explanation: '"Believe" states personal opinion.' },
        { type: 'multiple-choice', question: 'Combine clauses: "She studied hard. She passed."', options: ['Because she studied hard, she passed.', 'Although she studied, she passed.', 'Unless she studied, she passed.', 'If she studied, she passed.'], correctAnswers: [0], explanation: '"Because" shows cause-and-effect.' },
        { type: 'multiple-choice', question: 'Complete: "After the train _______, we left for the station."', options: ['arrived', 'has arrived', 'arrives', 'will arrive'], correctAnswers: [0], explanation: 'After + past simple needs past simple.' },
        { type: 'listening', question: 'Complete: "The main _______ is lack of resources."', audioPrompt: 'problem', options: ['issue', 'problem', 'situation', 'matter'], correctAnswers: [1], explanation: '"Problem" directly identifies the issue.' },
    ],
};
const level6FinalExam = {
    levelId: 6,
    title: 'Level 6 – Final Exam',
    description: 'Final examination covering all Level 6 content',
    content: {
        introduction: 'Welcome to your Level 6 Final Exam! This comprehensive exam tests your knowledge covering continuous tenses, advanced modals, passive voice, subjunctive mood, business communication, debating skills, literature and arts, and environmental issues.',
        objectives: [
            'Demonstrate mastery of all Level 6 content',
            'Apply knowledge of advanced tenses and modals',
            'Show understanding of formal communication',
            'Complete a comprehensive final assessment',
            'Show readiness for advancement to Level 7',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 6 materials. You will be tested on continuous tenses, modals, passive voice, subjunctive mood, business communication, debates, literature, and environmental topics. Do your best!',
        summary: 'You have completed the Level 6 Final Exam. This comprehensive assessment evaluates all your learning from Level 6.',
    },
    exercises: [
        { type: 'multiple-choice', question: 'Complete: "Right now, she _______ on an important project."', options: ['works', 'is working', 'has worked', 'worked'], correctAnswers: [1], explanation: 'Present continuous for action happening now.' },
        { type: 'listening', question: 'What was happening? "_______ for three months."', audioPrompt: 'has been working', options: ['is working', 'has been working', 'was working', 'works'], correctAnswers: [1], explanation: 'Present perfect continuous shows duration.' },
        { type: 'multiple-choice', question: 'Complete: "He _______ be at home. I am not sure."', options: ['must', 'might', 'will', 'is'], correctAnswers: [1], explanation: '"Might" expresses uncertainty.' },
        { type: 'listening', question: 'Complete passive: "The report _______ by tomorrow."', audioPrompt: 'must be finished', options: ['must finish', 'must be finished', 'should finish', 'must have finished'], correctAnswers: [1], explanation: 'Modal + be + past participle = passive.' },
        { type: 'multiple-choice', question: 'Complete formal: "Dear Sir/Madam, I would _______ information."', options: ['want', 'like', 'love', 'wish'], correctAnswers: [1], explanation: '"Would like" is formal professional language.' },
        { type: 'listening', question: 'How to start first debate argument?', audioPrompt: 'First of all', options: ['Obviously', 'First of all', 'Clearly', 'Everyone knows'], correctAnswers: [1], explanation: '"First of all" appropriately introduces arguments.' },
        { type: 'multiple-choice', question: 'What is symbolism in literature?', options: ['Using similar words', 'Objects represent ideas', 'Making rhymes', 'Exaggeration'], correctAnswers: [1], explanation: 'Symbolism uses objects to represent ideas.' },
        { type: 'listening', question: 'What does "foreshadowing" mean?', audioPrompt: 'Hinting at future', options: ['Ending the story', 'Hinting at future events', 'Describing past', 'Repeating'], correctAnswers: [1], explanation: 'Foreshadowing hints at events coming later.' },
        { type: 'multiple-choice', question: 'Complete: "What is the _______ footprint?"', options: ['environmental', 'carbon', 'ecological', 'natural'], correctAnswers: [1], explanation: '"Carbon footprint" measures environmental impact.' },
        { type: 'listening', question: 'Complete formally: "Could you kindly _______ the report?"', audioPrompt: 'send', options: ['sending', 'sent', 'send', 'have sent'], correctAnswers: [2], explanation: 'Use base form after "Could you kindly".' },
        { type: 'multiple-choice', question: 'Complete suggestion: "I suggest that he _______ her manager."', options: ['talks to', 'talk to', 'talked to', 'will talk'], correctAnswers: [1], explanation: 'Use base form after "suggest" (subjunctive).' },
        { type: 'listening', question: 'Complete wish: "I wish I _______ there."', audioPrompt: 'were', options: ['was', 'were', 'am', 'have been'], correctAnswers: [1], explanation: 'Use "were" in subjunctive wishes.' },
        { type: 'multiple-choice', question: 'Convert to passive: "They are building a new hospital."', options: ['A hospital is built', 'A hospital is being built', 'A hospital was built', 'A hospital will be built'], correctAnswers: [1], explanation: 'Present continuous becomes continuous passive.' },
        { type: 'listening', question: 'Complete academically: "The data _______ that reform is necessary."', audioPrompt: 'indicates', options: ['shows', 'indicates', 'means', 'tells'], correctAnswers: [1], explanation: '"Indicates" is appropriately formal for academic writing.' },
        { type: 'multiple-choice', question: 'How to respond to opposing view in debate?', options: ['You are wrong', 'While that is valid, I would argue...', 'That is stupid', 'Everyone disagrees'], correctAnswers: [1], explanation: 'Acknowledge view respectfully before refuting.' },
        { type: 'listening', question: 'Complete: "Protecting _______ is essential for wildlife."', audioPrompt: 'ecosystems', options: ['surroundings', 'ecosystems', 'weather', 'countries'], correctAnswers: [1], explanation: 'Ecosystems are interconnected systems.' },
        { type: 'multiple-choice', question: 'Complete closing email: "Yours _______,"', options: ['faithfully', 'sincerely', 'truly', 'genuinely'], correctAnswers: [1], explanation: '"Yours sincerely," is standard closing.' },
        { type: 'listening', question: 'Complete: "Please find _______ the documents."', audioPrompt: 'attached', options: ['attached', 'attach', 'attaching', 'attached with'], correctAnswers: [0], explanation: '"Please find attached" is standard professional phrase.' },
        { type: 'multiple-choice', question: 'What does "conservation" mean?', options: ['Discussing politics', 'Protecting resources', 'Changing nature', 'Building structures'], correctAnswers: [1], explanation: 'Conservation means protecting and preserving.' },
        { type: 'listening', question: 'Complete: "_______ energy is essential for sustainability."', audioPrompt: 'Renewable', options: ['Resources', 'Renewable', 'Recycled', 'Sustainable'], correctAnswers: [1], explanation: '"Renewable" refers to regenerating energy sources.' },
    ],
};
const level7FinalExam = {
    levelId: 7,
    title: 'Level 7 – Final Exam',
    description: 'Final examination covering all Level 7 content',
    content: {
        introduction: 'Welcome to your Level 7 Final Exam! This comprehensive exam tests your knowledge covering academic writing, formal vs. informal register, euphemisms, complex narratives, professional scenarios, cultural references, technology and innovation, and global issues.',
        objectives: [
            'Demonstrate mastery of all Level 7 content',
            'Apply knowledge of academic and formal writing',
            'Show understanding of nuanced communication',
            'Complete a comprehensive final assessment',
            'Show advanced English proficiency',
        ],
        mainContent: 'This exam contains 20 questions covering all Level 7 materials. You will be tested on academic writing, register, euphemisms, complex narratives, professional communication, cultural references, technology, and global issues. Do your best!',
        summary: 'You have completed the Level 7 Final Exam. This comprehensive assessment evaluates your advanced English proficiency.',
    },
    exercises: [
        { type: 'multiple-choice', question: 'What is a thesis statement?', options: ['Essay title', 'Main argument', 'A quote', 'Conclusion'], correctAnswers: [1], explanation: 'Thesis presents your main argument.' },
        { type: 'listening', question: 'How support arguments academically?', audioPrompt: 'with evidence', options: ['With opinions', 'With evidence', 'With stories', 'Without support'], correctAnswers: [1], explanation: 'Academic writing requires evidence-based arguments.' },
        { type: 'multiple-choice', question: 'Which is formal?', options: ['Gonna attend', 'I will be attending', 'Gonna be there', 'Will attend'], correctAnswers: [1], explanation: '"Will be attending" is formal.' },
        { type: 'listening', question: 'Complete informally: "I _______ at the beach."', audioPrompt: 'hung out', options: ['spent time', 'socialized', 'hung out', 'spent leisure'], correctAnswers: [2], explanation: '"Hung out" is casual/informal.' },
        { type: 'multiple-choice', question: 'What is a euphemism?', options: ['Loud noise', 'Mild word for harsh thing', 'Musical note', 'Flower'], correctAnswers: [1], explanation: 'Euphemism uses mild language for unpleasant topics.' },
        { type: 'listening', question: 'Which is euphemism?', audioPrompt: 'Passed away', options: ['Died', 'Passed away', 'Died suddenly', 'Ceased living'], correctAnswers: [1], explanation: '"Passed away" gently describes death.' },
        { type: 'multiple-choice', question: 'What creates character depth?', options: ['Appearance', 'Growth and contradiction', 'Difficult words', 'Repeating info'], correctAnswers: [1], explanation: 'Growth and contradictions make characters realistic.' },
        { type: 'listening', question: 'What is subplot?', audioPrompt: 'Secondary plot', options: ['Small town', 'Secondary plot parallel to main', 'Bad plan', 'Mistake'], correctAnswers: [1], explanation: 'Subplots enrich main narrative.' },
        { type: 'multiple-choice', question: 'How begin negotiation professionally?', options: ['I need this', 'Find mutually beneficial solution', 'My way', 'Take it'], correctAnswers: [1], explanation: 'Seek mutual benefit creates productive negotiation.' },
        { type: 'listening', question: 'Complete diplomatically: "While valid, I _______ propose..."', audioPrompt: 'would', options: ['can', 'would', 'must', 'should'], correctAnswers: [1], explanation: '"Would" offers alternative respectfully.' },
        { type: 'multiple-choice', question: 'What "Catch-22" reference?', options: ['Highway', 'Impossible situation', 'Sports game', 'Location'], correctAnswers: [1], explanation: '"Catch-22" alludes to impossible dilemma.' },
        { type: 'listening', question: 'Complete: "Like Don Quixote, he _______ windmills."', audioPrompt: 'tilted', options: ['fought', 'tilted', 'attacked', 'rushed'], correctAnswers: [1], explanation: '"Tilted at windmills" references futile efforts.' },
        { type: 'multiple-choice', question: 'What "Achilles heel" reference?', options: ['Opportunity', 'Fatal weakness', 'Bullet', 'Horse'], correctAnswers: [1], explanation: '"Achilles heel" references fatal weakness.' },
        { type: 'listening', question: 'What does AI stand?', audioPrompt: 'Artificial Intelligence', options: ['Video', 'Artificial Intelligence', 'App', 'Artist'], correctAnswers: [1], explanation: 'AI = Artificial Intelligence.' },
        { type: 'multiple-choice', question: 'What is geopolitical issue?', options: ['Location', 'Political conflict with geography', 'Climate', 'Travel'], correctAnswers: [1], explanation: 'Geopolitical involves politics and geography.' },
        { type: 'listening', question: 'Complete: "Global _______ requires cooperation."', audioPrompt: 'challenges', options: ['problems', 'challenges', 'difficulties', 'issues'], correctAnswers: [1], explanation: '"Challenges" appropriately describes complex issues.' },
        { type: 'multiple-choice', question: 'What sustainable development?', options: ['Building', 'Meeting needs without harming future', 'Economic growth', 'Technology'], correctAnswers: [1], explanation: 'Balances needs with future impact.' },
        { type: 'listening', question: 'What IoT mean?', audioPrompt: 'Internet of Things', options: ['Input or Table', 'Internet of Things', 'Internet on Television', 'Protocol'], correctAnswers: [1], explanation: 'IoT connects everyday devices to internet.' },
        { type: 'multiple-choice', question: 'Complete academic transition: "Furthermore, research _______ findings."', options: ['contradicts', 'disputes', 'reinforces', 'ignores'], correctAnswers: [2], explanation: '"Reinforces" strengthens/supports.' },
        { type: 'listening', question: 'Which uses passive (more formal)?', audioPrompt: 'The report was submitted', options: ['She submitted', 'The report was submitted', 'She turned in', 'The report given'], correctAnswers: [1], explanation: 'Passive voice is more formal.' },
    ],
};
const level8FinalExam = {
    levelId: 8,
    title: 'Level 8 – Final Exam',
    description: 'Final examination covering all Level 8 B2 content',
    content: {
        introduction: 'Welcome to your Level 8 Final Exam! This comprehensive exam tests your knowledge of mixed conditionals, advanced passive voice, future perfect and continuous, advanced relative clauses, phrasal verbs, reporting verbs, science and technology vocabulary, and modals of deduction.',
        objectives: [
            'Demonstrate B2 level mastery',
            'Apply advanced grammar structures',
            'Use sophisticated vocabulary',
            'Complete comprehensive assessment',
            'Show readiness for Level 9',
        ],
        mainContent: 'This exam contains 20 comprehensive questions covering all Level 8 materials. Do your best!',
        summary: 'You have completed the Level 8 Final Exam.',
    },
    exercises: [
        { type: 'multiple-choice', question: 'Complete the sentence: "If I _______ so much garlic last night, I wouldn\'t feel so thirsty now."', options: ['didn\'t eat', 'haven\'t eaten', 'hadn\'t eaten', 'wouldn\'t eat'], correctAnswers: [2], explanation: 'Mixed conditional: past action affects present state.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The Mona Lisa is known _______ by Leonardo da Vinci."', options: ['to paint', 'to be painting', 'to have been painted', 'that it was painted'], correctAnswers: [2], explanation: 'Impersonal passive with perfect infinitive.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "By the time we arrive at the cinema, the film _______."', options: ['will start', 'will have started', 'will be starting', 'starts'], correctAnswers: [1], explanation: 'Future perfect for action completed before future time.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "My sister, _______ is a doctor, works in London."', options: ['that', 'who', 'which', 'whose'], correctAnswers: [1], explanation: 'Non-defining clause requires "who" not "that".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "I refuse to _______ his terrible behavior any longer!"', options: ['put up with', 'get away with', 'look down on', 'catch up on'], correctAnswers: [0], explanation: '"Put up with" means to tolerate.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "He _______ having anything to do with the robbery."', options: ['refused', 'rejected', 'denied', 'declined'], correctAnswers: [2], explanation: '"Denied" + -ing for rejecting accusations.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "Researchers have discovered a new _______ of the virus."', options: ['strain', 'string', 'strand', 'stroke'], correctAnswers: [0], explanation: '"Strain" is correct term for virus variant.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "She got top marks in the test. She _______ studied very hard."', options: ['must have', 'can\'t have', 'should have', 'might have'], correctAnswers: [0], explanation: '"Must have" expresses strong certainty about past.' },
        { type: 'listening', question: 'Listen to the phrase: "I\'ll be working late tomorrow." What tense is this?', audioPrompt: 'Future Continuous', options: ['Future Simple', 'Future Perfect', 'Future Continuous', 'Present Continuous'], correctAnswers: [2], explanation: '"Will be working" is future continuous.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "I would be happier if I _______ a different career path years ago."', options: ['chose', 'had chosen', 'have chosen', 'would choose'], correctAnswers: [1], explanation: 'Mixed conditional: past action affects present.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "We need to _______ the roof repaired before winter."', options: ['make', 'have', 'do', 'take'], correctAnswers: [1], explanation: 'Causative: "have something done".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "At 10 AM tomorrow, I _______ an exam, so don\'t call me."', options: ['will take', 'will be taking', 'will have taken', 'am taking'], correctAnswers: [1], explanation: 'Future continuous for action in progress at specific future time.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The building, _______ was constructed in 1920, is now a museum."', options: ['that', 'which', 'where', 'whose'], correctAnswers: [1], explanation: 'Non-defining clause with comma requires "which".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "We had to _______ the match due to the heavy rain."', options: ['call off', 'put off', 'take off', 'turn off'], correctAnswers: [0], explanation: '"Call off" means to cancel.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "She _______ that we take a taxi instead of walking."', options: ['advised', 'told', 'suggested', 'offered'], correctAnswers: [2], explanation: '"Suggested" + that clause (without "to").' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The new smartphone features a completely _______ design."', options: ['innovative', 'obsolete', 'artificial', 'ancient'], correctAnswers: [0], explanation: '"Innovative" means new and creative.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "You _______ told me you were coming! I would have made lunch."', options: ['must have', 'might have', 'can\'t have', 'should have'], correctAnswers: [3], explanation: '"Should have" expresses criticism/regret.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The company is reported _______ heavy losses last quarter."', options: ['to make', 'to have made', 'making', 'that it made'], correctAnswers: [1], explanation: 'Impersonal passive with perfect infinitive for past.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "If they _______ the map, they wouldn\'t be lost right now."', options: ['checked', 'have checked', 'had checked', 'would check'], correctAnswers: [2], explanation: 'Mixed conditional: past action affects present.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The politicians finally managed to _______ a deal."', options: ['strike', 'hit', 'make', 'take'], correctAnswers: [0], explanation: '"Strike a deal" is the correct collocation.' },
    ],
};

const level9FinalExam = {
    levelId: 9,
    title: 'Level 9 – Final Exam',
    description: 'Final examination covering all Level 9 B2/C1 content',
    content: {
        introduction: 'Welcome to your Level 9 Final Exam! This comprehensive exam tests your knowledge of inversion, participle clauses, advanced modal structures, cleft sentences, perfect infinitives and gerunds, collocations, discourse markers, and global issues vocabulary.',
        objectives: [
            'Demonstrate advanced B2/C1 proficiency',
            'Apply sophisticated structures',
            'Use nuanced vocabulary',
            'Complete comprehensive assessment',
            'Show readiness for C1 level',
        ],
        mainContent: 'This exam contains 20 comprehensive questions covering all Level 9 materials. Do your best!',
        summary: 'You have completed the Level 9 Final Exam.',
    },
    exercises: [
        { type: 'multiple-choice', question: 'Complete the sentence: "Not once _______ at me during the entire meeting."', options: ['she looked', 'did she look', 'looked she', 'she did look'], correctAnswers: [1], explanation: 'After "not once" use inversion: auxiliary + subject.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "_______ the instructions carefully, he still made a mistake."', options: ['Read', 'Reading', 'Having read', 'To read'], correctAnswers: [2], explanation: 'Perfect participle shows completed action before main verb.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "I\'d rather you _______ me at home; I\'m trying to relax."', options: ['don\'t call', 'didn\'t call', 'not call', 'wouldn\'t call'], correctAnswers: [1], explanation: '"Would rather" + subject + past tense.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "It was the weather _______ ruined our holiday."', options: ['what', 'which', 'that', 'how'], correctAnswers: [2], explanation: 'It-cleft structure uses "that" for emphasis.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "She is thrilled _______ for the prestigious award."', options: ['to nominate', 'to be nominating', 'to have been nominated', 'having nominated'], correctAnswers: [2], explanation: 'Perfect passive infinitive: nomination happened before being thrilled.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The company went bankrupt due to _______ financial management."', options: ['grossly', 'poorly', 'appalling', 'heavily'], correctAnswers: [2], explanation: '"Appalling" (extremely bad) collocates with management.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "We enjoyed the holiday, _______ it was very expensive."', options: ['despite', 'albeit', 'however', 'nevertheless'], correctAnswers: [1], explanation: '"Albeit" means although/even though.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The United Nations imposed strict _______ on the country."', options: ['tariffs', 'sanctions', 'embargoes', 'quotas'], correctAnswers: [1], explanation: '"Sanctions" are penalties for breaking international law.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "Only after I left the house _______ I had forgotten my keys."', options: ['did I realize', 'I realized', 'I did realize', 'had I realized'], correctAnswers: [0], explanation: 'After "only after" use inversion.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "_______ by the police, the thief dropped the bag and ran."', options: ['Chasing', 'Chased', 'Having chased', 'To chase'], correctAnswers: [1], explanation: 'Past participle shows passive (thief was chased).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "It\'s high time you _______ to take responsibility for your actions."', options: ['learn', 'learning', 'learned', 'have learned'], correctAnswers: [2], explanation: '"It\'s high time" + past tense for overdue action.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "What I hated most about the movie _______ the ending."', options: ['were', 'is', 'was', 'being'], correctAnswers: [2], explanation: 'What-cleft + "was" (past) + emphasized element.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "He denied _______ anything about the missing documents."', options: ['to know', 'knowing', 'to have known', 'knew'], correctAnswers: [1], explanation: '"Deny" + gerund (-ing form).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "She has a _______ memory for names and faces."', options: ['photographic', 'visual', 'picture', 'graphic'], correctAnswers: [0], explanation: '"Photographic memory" is the fixed collocation.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The plan was ambitious; _______, it was completely unworkable."', options: ['furthermore', 'consequently', 'nevertheless', 'therefore'], correctAnswers: [2], explanation: '"Nevertheless" shows contrast despite ambition.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The activist spoke passionately about the need to _______ poverty."', options: ['eradicate', 'demolish', 'destroy', 'exterminate'], correctAnswers: [0], explanation: '"Eradicate" means completely eliminate (social issues).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "Never before _______ such a ridiculous excuse!"', options: ['I have heard', 'did I hear', 'have I heard', 'I heard'], correctAnswers: [2], explanation: 'After "never before" use present perfect inversion.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "_______ the situation, she decided to stay quiet."', options: ['Assessed', 'Assessing', 'Having assess', 'To assess'], correctAnswers: [1], explanation: 'Present participle shows simultaneous action.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "You had better _______ anyone about this secret."', options: ['not tell', 'not to tell', 'don\'t tell', 'didn\'t tell'], correctAnswers: [0], explanation: '"Had better not" + infinitive (without to).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The Prime Minister\'s speech was met with _______ applause."', options: ['thunderous', 'stormy', 'windy', 'raining'], correctAnswers: [0], explanation: '"Thunderous applause" is the standard collocation.' },
    ],
};

const level10FinalExam = {
    levelId: 10,
    title: 'Level 10 – Final Exam',
    description: 'Final examination covering all Level 10 C1 content',
    content: {
        introduction: 'Welcome to your Level 10 Final Exam! This comprehensive exam tests your knowledge of subjunctive mood, inverted conditionals, ellipsis and substitution, dependent prepositions, nuanced vocabulary, advanced phrasal verbs, idioms, and double comparatives.',
        objectives: [
            'Demonstrate C1 mastery',
            'Apply sophisticated grammar',
            'Use precise vocabulary',
            'Complete comprehensive assessment',
            'Show advanced proficiency',
        ],
        mainContent: 'This exam contains 20 comprehensive questions covering all Level 10 materials. Congratulations on reaching this level!',
        summary: 'You have completed the Level 10 Final Exam. Congratulations on achieving C1 level proficiency!',
    },
    exercises: [
        { type: 'multiple-choice', question: 'Complete the sentence: "It is imperative that the equipment _______ tested before use."', options: ['is', 'be', 'will be', 'are'], correctAnswers: [1], explanation: 'Mandative subjunctive: use base form "be".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "_______ I known about the traffic, I would have taken a different route."', options: ['Had', 'If', 'Have', 'Were'], correctAnswers: [0], explanation: 'Inverted conditional: "Had" replaces "If I had".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "He told me to rewrite the essay, and I plan _______."', options: ['to do', 'to', 'doing', 'do'], correctAnswers: [1], explanation: 'Ellipsis: "to" replaces "to rewrite it".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "Her behavior was completely incongruous _______ her usual calm demeanor."', options: ['to', 'with', 'for', 'from'], correctAnswers: [1], explanation: '"Incongruous with" is the correct preposition.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The author\'s writing style is known for being highly _______ and difficult to decipher."', options: ['lucid', 'opaque', 'transparent', 'pellucid'], correctAnswers: [1], explanation: '"Opaque" means unclear/difficult to understand.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "Despite the initial setbacks, they managed to pull the project _______."', options: ['off', 'through', 'out', 'over'], correctAnswers: [0], explanation: '"Pull off" means to succeed despite difficulties.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The new tax policy was a bone of _______ between the two political parties."', options: ['contention', 'argument', 'dispute', 'conflict'], correctAnswers: [0], explanation: '"Bone of contention" is the fixed idiom.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The harder you push him, the _______ he becomes."', options: ['more stubborn', 'most stubborn', 'stubborner', 'stubborn'], correctAnswers: [0], explanation: 'Double comparative: "the harder... the more stubborn".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "I request that she _______ present at the hearing."', options: ['is', 'be', 'will be', 'was'], correctAnswers: [1], explanation: 'Subjunctive after "request": use base form "be".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "_______ it not been for the seatbelt, he would have been seriously injured."', options: ['Had', 'Were', 'Was', 'Did'], correctAnswers: [0], explanation: 'Inverted third conditional: "Had it not been for".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "She promised to return the book, but I knew she never _______."', options: ['will', 'would', 'did', 'has'], correctAnswers: [1], explanation: 'Substitution: "would" replaces "would return it".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The committee is entirely devoid _______ any real power."', options: ['from', 'of', 'in', 'with'], correctAnswers: [1], explanation: '"Devoid of" means completely lacking.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The CEO was forced to step down after a highly _______ scandal."', options: ['auspicious', 'lucrative', 'damaging', 'beneficial'], correctAnswers: [2], explanation: '"Damaging" means harmful/destructive.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The negotiations broke _______ after neither side would compromise."', options: ['down', 'up', 'off', 'out'], correctAnswers: [0], explanation: '"Break down" means to fail/collapse.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "He really went out on a _______ to defend his colleague."', options: ['branch', 'limb', 'tree', 'twig'], correctAnswers: [1], explanation: '"Go out on a limb" means to take a risk.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "No sooner had the match begun _______ it started to pour with rain."', options: ['than', 'when', 'then', 'that'], correctAnswers: [0], explanation: '"No sooner... than" structure (inverted).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "It is crucial that he _______ his medication every day."', options: ['takes', 'take', 'took', 'will take'], correctAnswers: [1], explanation: 'Subjunctive: base form "take" after "crucial that".' },
        { type: 'multiple-choice', question: 'Complete the sentence: "But _______ her quick thinking, the fire would have spread."', options: ['for', 'by', 'with', 'to'], correctAnswers: [0], explanation: '"But for" means "if it were not for" (formal).' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The manager\'s demands were tantamount _______ extortion."', options: ['with', 'to', 'for', 'from'], correctAnswers: [1], explanation: '"Tantamount to" means equivalent to.' },
        { type: 'multiple-choice', question: 'Complete the sentence: "The project has been plagued by a _______ of problems since day one."', options: ['plethora', 'scarcity', 'dearth', 'paucity'], correctAnswers: [0], explanation: '"Plethora" means a large quantity/excess.' },
    ],
};

export const allLevelExams = {
    1: level1FinalExam,
    2: level2FinalExam,
    3: level3FinalExam,
    4: level4FinalExam,
    5: level5FinalExam,
    6: level6FinalExam,
    7: level7FinalExam,
    8: level8FinalExam,
    9: level9FinalExam,
    10: level10FinalExam,
};
export { level1FinalExam, level2FinalExam, level3FinalExam, level4FinalExam, level5FinalExam, level6FinalExam, level7FinalExam, level8FinalExam, level9FinalExam, level10FinalExam };
//# sourceMappingURL=examData.js.map