// LEVEL 8 - B2 (Upper-Intermediate)
export const level8Lessons = [
  {
    levelId: 8,
    lessonNumber: 1,
    title: 'Mixed Conditionals',
    description: 'Combine different conditional forms to express complex relationships between past and present.',
    content: {
      introduction: 'Mixed conditionals combine elements of different conditional types to express how past actions affect present situations or how present states relate to hypothetical past events.',
      objectives: [
        'Understand mixed conditional structures',
        'Combine past and present conditions',
        'Express complex hypothetical relationships',
        'Use mixed conditionals in context'
      ],
      mainContent: 'Mixed conditionals: If + past perfect, would + infinitive (past action → present result). If + past simple, would have + past participle (present state → hypothetical past).',
      summary: 'You can use mixed conditionals to express sophisticated cause-and-effect relationships across time periods.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "If I had taken that job in Paris, I _______ fluent in French by now."',
        options: ['will be', 'would be', 'would have been', 'am'],
        correctAnswers: [1],
        explanation: 'Past action (taking job) affects present state (being fluent), so we use: If + past perfect, would + infinitive.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "If she _______ so much time on her phone, she would have passed the exam yesterday."',
        options: ['didn\'t spend', 'hasn\'t spent', 'hadn\'t spent', 'doesn\'t spend'],
        correctAnswers: [0],
        explanation: 'Present habit (spending time on phone) affected past result (failing exam): If + past simple, would have + past participle.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I would be working in London now if I _______ the interview."',
        options: ['haven\'t failed', 'didn\'t fail', 'hadn\'t failed', 'wouldn\'t fail'],
        correctAnswers: [2],
        explanation: 'Past event (failing interview) affects present situation (not working in London).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "If they were paying attention, they _______ the mistake before they sent the email."',
        options: ['would spot', 'will spot', 'spotted', 'would have spotted'],
        correctAnswers: [3],
        explanation: 'Present state (being attentive) would have affected past action (spotting mistake).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "If I _______ you, I wouldn\'t have spoken to the manager like that."',
        options: ['was', 'am', 'were', 'have been'],
        correctAnswers: [2],
        explanation: 'Hypothetical present state (being you) relates to past action (speaking to manager).',
      },
    ],
    audioContent: [
      { text: 'mixed conditional', type: 'phrase', context: 'Grammar structure' },
      { text: 'hypothetical relationship', type: 'phrase', context: 'Grammar concept' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 2,
    title: 'Advanced Passive Voice',
    description: 'Use passive constructions in complex and impersonal contexts.',
    content: {
      introduction: 'Advanced passive voice includes impersonal constructions and causative forms used in formal and academic contexts.',
      objectives: [
        'Use impersonal passive constructions',
        'Form causative passive structures',
        'Apply passive in formal contexts',
        'Understand passive with reporting verbs'
      ],
      mainContent: 'Impersonal passive: "It is believed that...", "He is believed to...". Causative: "have/get something done". Passive with modals and perfect tenses.',
      summary: 'You can use sophisticated passive structures in formal and academic writing.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He is believed _______ the country under a false name."',
        options: ['to leave', 'to have left', 'leaving', 'that he left'],
        correctAnswers: [1],
        explanation: 'Impersonal passive with perfect infinitive indicates completed action: "to have left".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I need to _______ by Friday for the wedding."',
        options: ['have cut my hair', 'cut my hair', 'have my hair cut', 'had my hair cut'],
        correctAnswers: [2],
        explanation: 'Causative structure: "have + object + past participle" (someone else does it for you).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It _______ that the CEO is going to resign next month."',
        options: ['has rumoured', 'is rumoured', 'rumours', 'was rumouring'],
        correctAnswers: [1],
        explanation: 'Impersonal passive: "It is + past participle + that clause".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I don\'t like _______ what to do."',
        options: ['telling', 'to tell', 'being told', 'having told'],
        correctAnswers: [2],
        explanation: 'Passive gerund: "being + past participle" after verbs like "like/dislike".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The suspect is thought _______ in the local area."',
        options: ['to be hiding', 'hiding', 'that he hides', 'is hiding'],
        correctAnswers: [0],
        explanation: 'Impersonal passive with continuous infinitive for ongoing action.',
      },
    ],
    audioContent: [
      { text: 'impersonal passive', type: 'phrase', context: 'Grammar structure' },
      { text: 'causative', type: 'word', context: 'Grammar concept' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 3,
    title: 'Future Perfect and Future Continuous',
    description: 'Express actions in progress or completed in the future.',
    content: {
      introduction: 'Future perfect and future continuous describe sophisticated relationships between future time points.',
      objectives: [
        'Use future continuous for ongoing future actions',
        'Use future perfect for completed future actions',
        'Understand time relationships in the future',
        'Apply both tenses appropriately'
      ],
      mainContent: 'Future continuous: will be + -ing (action in progress at future time). Future perfect: will have + past participle (action completed before future time).',
      summary: 'You can express complex future time relationships with precision.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "This time next week, I _______ on a beach in Hawaii."',
        options: ['will relax', 'will be relaxing', 'will have relaxed', 'relax'],
        correctAnswers: [1],
        explanation: 'Future continuous describes action in progress at specific future time.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "By the time you arrive, we _______ cooking dinner."',
        options: ['will finish', 'are finishing', 'will have finished', 'will be finishing'],
        correctAnswers: [2],
        explanation: 'Future perfect indicates action will be completed before another future event.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Please don\'t call me at 8 PM. I _______ dinner with my family."',
        options: ['will have', 'have', 'will be having', 'will have had'],
        correctAnswers: [2],
        explanation: 'Future continuous describes action in progress at specific future time (8 PM).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "By the end of this year, she _______ at the company for a decade."',
        options: ['will work', 'is working', 'will be working', 'will have been working'],
        correctAnswers: [3],
        explanation: 'Future perfect continuous for duration up to future point.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Do you think you _______ the report by 5 PM?"',
        options: ['will have completed', 'will be completing', 'are completing', 'will complete'],
        correctAnswers: [0],
        explanation: 'Future perfect for completion before specific future time.',
      },
    ],
    audioContent: [
      { text: 'future continuous', type: 'phrase', context: 'Tense' },
      { text: 'future perfect', type: 'phrase', context: 'Tense' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 4,
    title: 'Relative Clauses (Advanced)',
    description: 'Use non-defining and complex relative clauses.',
    content: {
      introduction: 'Advanced relative clauses include non-defining clauses, quantifiers, and prepositional structures.',
      objectives: [
        'Distinguish defining from non-defining clauses',
        'Use relative pronouns with prepositions',
        'Apply quantifiers in relative clauses',
        'Master formal relative structures'
      ],
      mainContent: 'Non-defining: extra information with commas. Prepositions: "for which", "to whom". Quantifiers: "some of whom", "none of which".',
      summary: 'You use sophisticated relative clause structures in formal writing.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The man _______ car was stolen reported it to the police."',
        options: ['who', 'that', 'whose', 'whom'],
        correctAnswers: [2],
        explanation: '"Whose" shows possession in relative clauses.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "My brother, _______ lives in New York, is coming to visit."',
        options: ['that', 'which', 'who', 'whose'],
        correctAnswers: [2],
        explanation: 'Non-defining clause with commas requires "who" (not "that").',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "This is the company for _______ I have worked for the last five years."',
        options: ['that', 'which', 'whom', 'where'],
        correctAnswers: [1],
        explanation: 'Formal structure with preposition: "for which".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She offered me a coffee, _______ was exactly what I needed."',
        options: ['that', 'which', 'what', 'it'],
        correctAnswers: [1],
        explanation: '"Which" refers to entire previous clause in non-defining relative clause.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "There were ten students in the class, none of _______ passed the test."',
        options: ['which', 'them', 'who', 'whom'],
        correctAnswers: [3],
        explanation: 'Formal quantifier structure: "none of whom" for people.',
      },
    ],
    audioContent: [
      { text: 'non-defining clause', type: 'phrase', context: 'Grammar' },
      { text: 'relative pronoun', type: 'phrase', context: 'Grammar' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 5,
    title: 'Phrasal Verbs (B2 Level)',
    description: 'Master advanced phrasal verbs in context.',
    content: {
      introduction: 'B2-level phrasal verbs express nuanced meanings in formal and informal contexts.',
      objectives: [
        'Understand advanced phrasal verb meanings',
        'Use phrasal verbs appropriately',
        'Distinguish similar phrasal verbs',
        'Apply phrasal verbs in context'
      ],
      mainContent: 'Advanced phrasal verbs: put up with (tolerate), get over (recover), put off (postpone), catch up (meet and talk), pluck up (gather courage).',
      summary: 'You use advanced phrasal verbs naturally in conversation and writing.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I can\'t _______ this loud music anymore! I\'m going to complain."',
        options: ['put up with', 'get away with', 'look forward to', 'catch up on'],
        correctAnswers: [0],
        explanation: '"Put up with" means to tolerate something unpleasant.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It took him a long time to _______ the flu."',
        options: ['get off', 'get over', 'get down', 'get through'],
        correctAnswers: [1],
        explanation: '"Get over" means to recover from illness or difficulty.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The meeting has been _______ until next Wednesday."',
        options: ['put off', 'called off', 'taken off', 'turned off'],
        correctAnswers: [0],
        explanation: '"Put off" means to postpone or delay.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I bumped into an old friend and we decided to _______ over a coffee."',
        options: ['bring up', 'catch up', 'take over', 'look up'],
        correctAnswers: [1],
        explanation: '"Catch up" means to meet and share recent news.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She finally _______ the courage to ask for a promotion."',
        options: ['worked out', 'came up', 'plucked up', 'carried out'],
        correctAnswers: [2],
        explanation: '"Pluck up" means to summon or gather (courage, nerve).',
      },
    ],
    audioContent: [
      { text: 'phrasal verb', type: 'phrase', context: 'Grammar' },
      { text: 'put up with', type: 'phrase', context: 'Tolerate' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 6,
    title: 'Advanced Reporting Verbs',
    description: 'Use precise reporting verbs for different speech acts.',
    content: {
      introduction: 'Advanced reporting verbs express specific attitudes and speech functions beyond "say" and "tell".',
      objectives: [
        'Use reporting verbs with correct patterns',
        'Express different speech acts accurately',
        'Understand verb + preposition combinations',
        'Apply reporting verbs in context'
      ],
      mainContent: 'Reporting verbs: deny + -ing, insist on + -ing, warn + object + to, admit + -ing, suggest + that clause.',
      summary: 'You report speech precisely using a range of reporting verbs.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The suspect _______ stealing the money."',
        options: ['refused', 'denied', 'rejected', 'warned'],
        correctAnswers: [1],
        explanation: '"Deny" + -ing is used for rejecting accusations.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She _______ on paying for the meal."',
        options: ['insisted', 'suggested', 'offered', 'demanded'],
        correctAnswers: [0],
        explanation: '"Insist on" + -ing expresses strong determination.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He _______ me to leave the building immediately."',
        options: ['suggested', 'said', 'warned', 'threatened'],
        correctAnswers: [2],
        explanation: '"Warn" + object + to infinitive gives advice about danger.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "They _______ breaking the antique vase."',
        options: ['admitted', 'accused', 'blamed', 'refused'],
        correctAnswers: [0],
        explanation: '"Admit" + -ing means to confess or acknowledge.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "My boss _______ that we start the meeting early."',
        options: ['told', 'suggested', 'asked', 'advised'],
        correctAnswers: [1],
        explanation: '"Suggest" + that clause (without "to") for proposals.',
      },
    ],
    audioContent: [
      { text: 'reporting verb', type: 'phrase', context: 'Grammar' },
      { text: 'speech act', type: 'phrase', context: 'Communication' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 7,
    title: 'Vocabulary: Science and Technology',
    description: 'Discuss scientific concepts and technological advances.',
    content: {
      introduction: 'Scientific and technological vocabulary enables discussion of research, innovation, and discovery.',
      objectives: [
        'Use scientific terminology correctly',
        'Discuss technological concepts',
        'Understand research-related vocabulary',
        'Express scientific processes'
      ],
      mainContent: 'Key terms: photosynthesis, breakthrough, artificial intelligence, distant galaxies, clinical trials, strain (of virus).',
      summary: 'You discuss science and technology with appropriate vocabulary.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is the process by which plants make their food using sunlight?',
        options: ['Evolution', 'Photosynthesis', 'Respiration', 'Genetics'],
        correctAnswers: [1],
        explanation: 'Photosynthesis is the process plants use to convert sunlight into energy.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The scientists made a major _______ in cancer research."',
        options: ['breakout', 'breakdown', 'breakthrough', 'breakaway'],
        correctAnswers: [2],
        explanation: 'A "breakthrough" is a major discovery or advancement.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Many appliances are now equipped with _______ intelligence."',
        options: ['fake', 'false', 'artificial', 'synthetic'],
        correctAnswers: [2],
        explanation: '"Artificial intelligence" (AI) refers to machine learning systems.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The telescope allows us to observe _______ galaxies."',
        options: ['distant', 'obsolete', 'innovative', 'virtual'],
        correctAnswers: [0],
        explanation: '"Distant" describes galaxies far away in space.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Before a drug is approved, it must undergo rigorous clinical _______."',
        options: ['attempts', 'trials', 'errors', 'experiments'],
        correctAnswers: [1],
        explanation: '"Clinical trials" are research studies testing medical treatments.',
      },
    ],
    audioContent: [
      { text: 'photosynthesis', type: 'word', context: 'Biology' },
      { text: 'breakthrough', type: 'word', context: 'Research' },
      { text: 'artificial intelligence', type: 'phrase', context: 'Technology' },
    ],
  },
  {
    levelId: 8,
    lessonNumber: 8,
    title: 'Modals of Deduction (Past & Present)',
    description: 'Express certainty and possibility about past and present situations.',
    content: {
      introduction: 'Modal verbs of deduction express how certain we are about situations based on evidence.',
      objectives: [
        'Use modals for present deduction',
        'Use modals for past deduction',
        'Express degrees of certainty',
        'Distinguish between different modal meanings'
      ],
      mainContent: 'Present: must be (certain), can\'t be (impossible), might be (possible). Past: must have, can\'t have, should have, might have.',
      summary: 'You express logical deductions about present and past situations accurately.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She\'s not answering her phone. She _______ asleep."',
        options: ['must be', 'can be', 'should be', 'ought to be'],
        correctAnswers: [0],
        explanation: '"Must be" expresses strong certainty about present situation.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "You _______ seen John yesterday; he is currently in Australia!"',
        options: ['must have', 'can\'t have', 'should have', 'might have'],
        correctAnswers: [1],
        explanation: '"Can\'t have" expresses impossibility about past event.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I don\'t know why she didn\'t say hello. She _______ not have seen you."',
        options: ['must', 'can', 'should', 'might'],
        correctAnswers: [3],
        explanation: '"Might not have" expresses possibility that something didn\'t happen.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He failed the exam. He _______ studied harder."',
        options: ['must have', 'can\'t have', 'should have', 'might have'],
        correctAnswers: [2],
        explanation: '"Should have" expresses criticism or regret about past action.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "There\'s a lot of traffic. The accident _______ caused a delay."',
        options: ['must have', 'can\'t have', 'should have', 'ought to have'],
        correctAnswers: [0],
        explanation: '"Must have" expresses strong certainty about past cause.',
      },
    ],
    audioContent: [
      { text: 'modal of deduction', type: 'phrase', context: 'Grammar' },
      { text: 'certainty', type: 'word', context: 'Degree of confidence' },
    ],
  },
];

// LEVEL 9 - B2/C1 (Advanced Transition)
export const level9Lessons = [
  {
    levelId: 9,
    lessonNumber: 1,
    title: 'Inversion (Negative Adverbials)',
    description: 'Use formal inversion structures for emphasis.',
    content: {
      introduction: 'Inversion with negative adverbials creates formal, emphatic expressions used in literary and formal contexts.',
      objectives: [
        'Recognize negative adverbials requiring inversion',
        'Form inverted structures correctly',
        'Use inversion for emphasis',
        'Apply inversion in formal writing'
      ],
      mainContent: 'After negative adverbials (hardly, scarcely, rarely, never, not only, under no circumstances), use question word order for emphasis.',
      summary: 'You use inversion structures to create formal, emphatic expressions.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Hardly _______ down when the phone rang."',
        options: ['had I sat', 'I had sat', 'did I sit', 'I sat'],
        correctAnswers: [0],
        explanation: 'After "hardly" use inversion: hardly + auxiliary + subject + verb.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Under no circumstances _______ open this door."',
        options: ['you should', 'should you', 'you must', 'must you to'],
        correctAnswers: [1],
        explanation: 'After "under no circumstances" invert modal and subject.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Not only _______ the exam, but she also got the highest score."',
        options: ['she passed', 'passed she', 'did she pass', 'she did pass'],
        correctAnswers: [2],
        explanation: 'After "not only" use auxiliary + subject + verb.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Scarcely _______ the house when it started to pour with rain."',
        options: ['we had left', 'had we left', 'did we leave', 'we left'],
        correctAnswers: [1],
        explanation: 'After "scarcely" invert auxiliary and subject.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Rarely _______ such a magnificent performance."',
        options: ['have I seen', 'I have seen', 'I saw', 'did I saw'],
        correctAnswers: [0],
        explanation: 'After "rarely" use have/has + subject + past participle.',
      },
    ],
    audioContent: [
      { text: 'inversion', type: 'word', context: 'Grammar structure' },
      { text: 'negative adverbial', type: 'phrase', context: 'Grammar term' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 2,
    title: 'Participle Clauses',
    description: 'Use participle clauses to create concise, sophisticated sentences.',
    content: {
      introduction: 'Participle clauses replace full clauses, creating more elegant and economical expressions.',
      objectives: [
        'Form present participle clauses',
        'Form past participle clauses',
        'Form perfect participle clauses',
        'Use participle clauses appropriately'
      ],
      mainContent: 'Present participle: -ing form (active). Past participle: -ed form (passive). Perfect participle: having + past participle (completed action).',
      summary: 'You use participle clauses to create concise, sophisticated sentences.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ by the long journey, he fell asleep on the sofa."',
        options: ['Exhausting', 'Exhausted', 'Having exhausted', 'To exhaust'],
        correctAnswers: [1],
        explanation: 'Past participle shows passive meaning (he was exhausted).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ the book, I can highly recommend it."',
        options: ['Read', 'Reading', 'Having read', 'To read'],
        correctAnswers: [2],
        explanation: 'Perfect participle shows completed action before main verb.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ at the right angle, the building looks like a spaceship."',
        options: ['Viewing', 'Viewed', 'Having viewed', 'To view'],
        correctAnswers: [1],
        explanation: 'Past participle shows passive (when it is viewed).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Not _______ what to do, she called her manager for advice."',
        options: ['knowing', 'known', 'having known', 'knew'],
        correctAnswers: [0],
        explanation: 'Present participle with "not" shows reason.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ the room, he realized he had forgotten his keys."',
        options: ['Entering', 'Entered', 'Having entered', 'To enter'],
        correctAnswers: [0],
        explanation: 'Present participle shows simultaneous action.',
      },
    ],
    audioContent: [
      { text: 'participle clause', type: 'phrase', context: 'Grammar' },
      { text: 'perfect participle', type: 'phrase', context: 'Grammar form' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 3,
    title: 'Advanced Modal Structures',
    description: 'Use sophisticated modal expressions for preferences and urgency.',
    content: {
      introduction: 'Advanced modal structures express preferences, urgency, and necessity in formal contexts.',
      objectives: [
        'Use "would rather" for preferences',
        'Use "it\'s high time" for urgency',
        'Use "had better" for strong advice',
        'Understand modal nuances'
      ],
      mainContent: 'Would rather + subject + past tense. It\'s high time + past tense. Had better + infinitive (without to).',
      summary: 'You express preferences, urgency, and necessity with sophisticated modal structures.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I would rather you _______ smoke in the house."',
        options: ['don\'t', 'didn\'t', 'not', 'wouldn\'t'],
        correctAnswers: [1],
        explanation: '"Would rather" + subject + past tense for present/future preference.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It\'s high time we _______ the airport."',
        options: ['leave', 'are leaving', 'left', 'had left'],
        correctAnswers: [2],
        explanation: '"It\'s high time" + past tense expresses urgency.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "You had better _______ late for the interview."',
        options: ['not be', 'not to be', 'don\'t be', 'aren\'t'],
        correctAnswers: [0],
        explanation: '"Had better not" + infinitive (without to) for strong advice.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I would sooner you _______ tell him the truth just yet."',
        options: ['didn\'t', 'don\'t', 'not', 'wouldn\'t'],
        correctAnswers: [0],
        explanation: '"Would sooner" + subject + past tense expresses preference.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It\'s about time you _______ taking your studies seriously."',
        options: ['start', 'started', 'are starting', 'have started'],
        correctAnswers: [1],
        explanation: '"It\'s about time" + past tense expresses something overdue.',
      },
    ],
    audioContent: [
      { text: 'would rather', type: 'phrase', context: 'Modal expression' },
      { text: 'had better', type: 'phrase', context: 'Modal expression' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 4,
    title: 'Cleft Sentences (Emphasis)',
    description: 'Use cleft sentences to emphasize specific information.',
    content: {
      introduction: 'Cleft sentences split information to emphasize particular elements.',
      objectives: [
        'Form "it" cleft sentences',
        'Form "what" cleft sentences',
        'Use "all" cleft sentences',
        'Choose appropriate cleft structures'
      ],
      mainContent: 'It-cleft: "It is/was... that/who...". What-cleft: "What I need is...". All-cleft: "All I want is...".',
      summary: 'You use cleft sentences to emphasize key information effectively.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "What I don\'t understand _______ why he left so suddenly."',
        options: ['it is', 'is', 'that is', 'being'],
        correctAnswers: [1],
        explanation: '"What" clause + "is" + emphasized information.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It was John _______ broke the window."',
        options: ['who', 'what', 'which', 'whom'],
        correctAnswers: [0],
        explanation: '"It was" + person + "who" + verb emphasizes the person.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "All I want _______ a little peace and quiet."',
        options: ['is', 'are', 'to be', 'it is'],
        correctAnswers: [0],
        explanation: '"All I want" + "is" (singular verb) + emphasized thing.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ the manager that I need to speak to."',
        options: ['There is', 'It is', 'What is', 'He is'],
        correctAnswers: [1],
        explanation: '"It is" + emphasized noun + relative clause.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The reason _______ I am calling is to confirm my appointment."',
        options: ['why', 'because', 'what', 'which'],
        correctAnswers: [0],
        explanation: '"The reason why" cleft emphasizes the reason.',
      },
    ],
    audioContent: [
      { text: 'cleft sentence', type: 'phrase', context: 'Grammar structure' },
      { text: 'emphasis', type: 'word', context: 'Communication' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 5,
    title: 'Perfect Infinitives and Gerunds',
    description: 'Use perfect forms to express completed or past actions.',
    content: {
      introduction: 'Perfect infinitives and gerunds refer to actions completed before the main verb.',
      objectives: [
        'Form perfect infinitives',
        'Form perfect gerunds',
        'Understand time relationships',
        'Use perfect forms correctly'
      ],
      mainContent: 'Perfect infinitive: to have + past participle. Perfect gerund: having + past participle. Used after certain verbs to show earlier action.',
      summary: 'You use perfect infinitives and gerunds to express completed actions.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She claims _______ the president, but nobody believes her."',
        options: ['to meet', 'to have met', 'meeting', 'having met'],
        correctAnswers: [1],
        explanation: 'Perfect infinitive shows the meeting happened before the claim.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He regrets _______ harder when he was at university."',
        options: ['not to study', 'not studying', 'not to have studied', 'to not study'],
        correctAnswers: [1],
        explanation: '"Regret" + -ing for past actions (not perfect here as time is specified).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I appreciate _______ me the opportunity to present my ideas."',
        options: ['you to give', 'your giving', 'you give', 'that you give'],
        correctAnswers: [1],
        explanation: 'Possessive + gerund after "appreciate".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He was punished for _______ the company\'s rules."',
        options: ['having broken', 'to break', 'break', 'to have broken'],
        correctAnswers: [0],
        explanation: 'Perfect gerund shows breaking happened before punishment.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "They are proud _______ the tournament for the third time."',
        options: ['to win', 'to have won', 'winning', 'having win'],
        correctAnswers: [1],
        explanation: 'Perfect infinitive: winning happened before feeling proud.',
      },
    ],
    audioContent: [
      { text: 'perfect infinitive', type: 'phrase', context: 'Grammar' },
      { text: 'perfect gerund', type: 'phrase', context: 'Grammar' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 6,
    title: 'Collocations (Strong & Fixed)',
    description: 'Use natural word combinations that native speakers expect.',
    content: {
      introduction: 'Strong collocations are fixed word combinations that sound natural and idiomatic.',
      objectives: [
        'Recognize strong collocations',
        'Use collocations appropriately',
        'Avoid incorrect combinations',
        'Expand collocation knowledge'
      ],
      mainContent: 'Common collocations: go blank (mind), tough rules, roaring success, highly unlikely, take exception to.',
      summary: 'You use natural collocations that make your English sound more native.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I completely forgot her birthday. My mind just went completely _______."',
        options: ['empty', 'blind', 'blank', 'dark'],
        correctAnswers: [2],
        explanation: '"Go blank" is the correct collocation for forgetting suddenly.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The government has introduced strictly _______ rules on immigration."',
        options: ['heavy', 'tough', 'hard', 'stiff'],
        correctAnswers: [1],
        explanation: '"Tough rules" is the standard collocation.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Despite the bad weather, the festival was a _______ success."',
        options: ['roaring', 'shouting', 'crying', 'screaming'],
        correctAnswers: [0],
        explanation: '"Roaring success" means a huge, emphatic success.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It is highly _______ that he will get the job without any experience."',
        options: ['improbable', 'impossible', 'unlikely', 'doubtful'],
        correctAnswers: [0],
        explanation: '"Highly improbable" is a strong collocation.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She took _______ exception to his rude comments."',
        options: ['strong', 'heavy', 'hard', 'deep'],
        correctAnswers: [0],
        explanation: '"Take strong exception" means to be very offended.',
      },
    ],
    audioContent: [
      { text: 'collocation', type: 'word', context: 'Word combination' },
      { text: 'roaring success', type: 'phrase', context: 'Idiom' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 7,
    title: 'Discourse Markers and Linkers',
    description: 'Use sophisticated connectors to structure complex arguments.',
    content: {
      introduction: 'Discourse markers and linkers create coherence and show relationships between ideas.',
      objectives: [
        'Use contrastive linkers',
        'Use additive linkers',
        'Use causal linkers',
        'Structure complex arguments'
      ],
      mainContent: 'Contrast: nevertheless, conversely, despite. Addition: moreover, furthermore, besides. Cause: owing to, consequently, accordingly.',
      summary: 'You structure complex arguments with sophisticated discourse markers.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The weather was terrible; _______, we still had a great time."',
        options: ['moreover', 'furthermore', 'nevertheless', 'consequently'],
        correctAnswers: [2],
        explanation: '"Nevertheless" shows contrast despite bad weather.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ the heavy rain, the football match went ahead as planned."',
        options: ['Although', 'Despite', 'In spite', 'However'],
        correctAnswers: [1],
        explanation: '"Despite" + noun phrase (not clause) shows contrast.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He is highly intelligent; _______, he lacks practical common sense."',
        options: ['conversely', 'subsequently', 'accordingly', 'therefore'],
        correctAnswers: [0],
        explanation: '"Conversely" shows opposite or contrasting characteristic.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The project was delayed, _______ largely to supply chain issues."',
        options: ['because', 'since', 'owing', 'resulting'],
        correctAnswers: [2],
        explanation: '"Owing" (+ to) is formal way to express cause.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ being a great musician, he is also a talented painter."',
        options: ['Beside', 'Besides', 'Except', 'Apart'],
        correctAnswers: [1],
        explanation: '"Besides" means "in addition to".',
      },
    ],
    audioContent: [
      { text: 'discourse marker', type: 'phrase', context: 'Grammar' },
      { text: 'linker', type: 'word', context: 'Connector' },
    ],
  },
  {
    levelId: 9,
    lessonNumber: 8,
    title: 'Global Issues and Politics',
    description: 'Discuss international affairs and political concepts.',
    content: {
      introduction: 'Vocabulary for discussing political systems, international relations, and global challenges.',
      objectives: [
        'Use political vocabulary accurately',
        'Discuss economic concepts',
        'Understand international relations terms',
        'Express political opinions appropriately'
      ],
      mainContent: 'Key terms: economic stagnation, curtail emissions, scarcity of resources, tax evasion, ceasefire, sanctions.',
      summary: 'You discuss global politics and economics with appropriate vocabulary.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The country is experiencing severe economic _______."',
        options: ['stagnation', 'inflation', 'currency', 'monopoly'],
        correctAnswers: [0],
        explanation: '"Economic stagnation" means lack of growth or development.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The government has pledged to _______ carbon emissions by 20%."',
        options: ['mitigate', 'alleviate', 'curtail', 'diminish'],
        correctAnswers: [2],
        explanation: '"Curtail" means to reduce or limit.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Many developing nations suffer from a _______ of natural resources."',
        options: ['scarcity', 'surplus', 'abundance', 'majority'],
        correctAnswers: [0],
        explanation: '"Scarcity" means shortage or lack.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The new laws are an attempt to crack down on tax _______."',
        options: ['evasion', 'avoidance', 'exemption', 'deduction'],
        correctAnswers: [0],
        explanation: '"Tax evasion" is illegal non-payment of taxes.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The two sides agreed to a temporary _______ to negotiate peace."',
        options: ['ceasefire', 'treaty', 'alliance', 'sanction'],
        correctAnswers: [0],
        explanation: '"Ceasefire" is a temporary stop to fighting.',
      },
    ],
    audioContent: [
      { text: 'economic stagnation', type: 'phrase', context: 'Economics' },
      { text: 'ceasefire', type: 'word', context: 'International relations' },
      { text: 'sanctions', type: 'word', context: 'Politics' },
    ],
  },
];

// LEVEL 10 - C1 (Advanced)
export const level10Lessons = [
  {
    levelId: 10,
    lessonNumber: 1,
    title: 'The Subjunctive (Mandative)',
    description: 'Use subjunctive mood in formal demands and recommendations.',
    content: {
      introduction: 'The mandative subjunctive is used after verbs of demand, suggestion, and importance in formal English.',
      objectives: [
        'Recognize mandative verbs',
        'Form subjunctive correctly',
        'Use subjunctive in formal contexts',
        'Distinguish subjunctive from indicative'
      ],
      mainContent: 'After verbs like suggest, demand, insist, recommend, it is essential/vital that... use base form (subjunctive): "I suggest that he go" not "goes".',
      summary: 'You use the subjunctive mood correctly in formal and academic contexts.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It is essential that he _______ the documents immediately."',
        options: ['signs', 'sign', 'signed', 'will sign'],
        correctAnswers: [1],
        explanation: 'After "it is essential that" use base form (subjunctive).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The board demanded that the manager _______ from his position."',
        options: ['resigns', 'resign', 'resigned', 'will resign'],
        correctAnswers: [1],
        explanation: 'After "demanded that" use base form (subjunctive).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I suggest that she _______ a lawyer before making a statement."',
        options: ['consults', 'consult', 'consulted', 'is consulting'],
        correctAnswers: [1],
        explanation: 'After "suggest that" use base form (subjunctive).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It is vital that they _______ informed of the changes."',
        options: ['are', 'be', 'will be', 'have been'],
        correctAnswers: [1],
        explanation: 'After "it is vital that" use "be" (subjunctive form).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The doctor recommended that he _______ his salt intake."',
        options: ['reduces', 'reduce', 'reduced', 'will reduce'],
        correctAnswers: [1],
        explanation: 'After "recommended that" use base form (subjunctive).',
      },
    ],
    audioContent: [
      { text: 'subjunctive mood', type: 'phrase', context: 'Grammar' },
      { text: 'mandative', type: 'word', context: 'Grammar term' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 2,
    title: 'Advanced Conditionals (Inverted & Nuanced)',
    description: 'Use formal inverted conditional structures.',
    content: {
      introduction: 'Formal conditionals use inversion instead of "if" in literary and formal writing.',
      objectives: [
        'Form inverted conditionals',
        'Use "but for" structures',
        'Use "given that" expressions',
        'Apply formal conditionals appropriately'
      ],
      mainContent: 'Inversion: "Should you need..." (= If you need), "Had I known..." (= If I had known), "Were it not for..." (= If it were not for).',
      summary: 'You use formal inverted conditionals in sophisticated writing.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ you need any further assistance, please do not hesitate to contact me."',
        options: ['Should', 'Would', 'Could', 'Might'],
        correctAnswers: [0],
        explanation: '"Should" replaces "if" in formal first conditional.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ I known the outcome, I would never have agreed to the plan."',
        options: ['Have', 'Had', 'Did', 'Were'],
        correctAnswers: [1],
        explanation: '"Had" replaces "if" in formal third conditional.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ it not for your financial support, the project would have failed."',
        options: ['Was', 'Had', 'Were', 'Did'],
        correctAnswers: [2],
        explanation: '"Were it not for" is formal way to express "if it were not for".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "But _______ the quick actions of the pilot, the plane would have crashed."',
        options: ['for', 'with', 'to', 'by'],
        correctAnswers: [0],
        explanation: '"But for" means "if it were not for" (formal).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "_______ that he is highly qualified, he still lacks practical experience."',
        options: ['Providing', 'Given', 'Assuming', 'Suppose'],
        correctAnswers: [1],
        explanation: '"Given that" acknowledges a fact while introducing contrast.',
      },
    ],
    audioContent: [
      { text: 'inverted conditional', type: 'phrase', context: 'Grammar' },
      { text: 'formal structure', type: 'phrase', context: 'Style' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 3,
    title: 'Ellipsis and Substitution',
    description: 'Omit repeated elements for conciseness.',
    content: {
      introduction: 'Ellipsis and substitution avoid repetition by omitting or replacing repeated words.',
      objectives: [
        'Use ellipsis correctly',
        'Use substitution words',
        'Maintain clarity while being concise',
        'Apply in formal contexts'
      ],
      mainContent: 'Ellipsis: "I want to go" → "to". Substitution: "did", "do", "so", "not". "Some prefer tea, others coffee".',
      summary: 'You use ellipsis and substitution to create concise, sophisticated sentences.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I didn\'t want to go to the party, but my friends convinced me _______."',
        options: ['to go', 'to', 'going', 'for it'],
        correctAnswers: [1],
        explanation: 'Ellipsis: "to" replaces "to go" to avoid repetition.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She doesn\'t play the piano as well as she used _______."',
        options: ['to play', 'to', 'playing', 'play'],
        correctAnswers: [1],
        explanation: 'Ellipsis: "to" after "used to" avoids repeating verb.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "I thought it would rain, and it _______."',
        options: ['did', 'was', 'had', 'did rain'],
        correctAnswers: [0],
        explanation: 'Substitution: "did" replaces "rained".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He said he would help me, but I doubt he _______."',
        options: ['will', 'does', 'has', 'would'],
        correctAnswers: [0],
        explanation: 'Substitution: "will" (present perspective) replaces "will help".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Some people prefer tea, while _______ prefer coffee."',
        options: ['another', 'others', 'the other', 'other'],
        correctAnswers: [1],
        explanation: '"Others" substitutes for "other people".',
      },
    ],
    audioContent: [
      { text: 'ellipsis', type: 'word', context: 'Grammar' },
      { text: 'substitution', type: 'word', context: 'Grammar technique' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 4,
    title: 'Advanced Dependent Prepositions',
    description: 'Use correct prepositions with adjectives and verbs.',
    content: {
      introduction: 'Many adjectives and verbs require specific prepositions to express particular meanings.',
      objectives: [
        'Learn adjective + preposition patterns',
        'Learn verb + preposition patterns',
        'Distinguish similar patterns',
        'Use prepositions accurately'
      ],
      mainContent: 'Common patterns: conducive to, devoid of, proficient in, obsessed with, disproportionate to.',
      summary: 'You use dependent prepositions correctly in formal contexts.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The noise from the street is not conducive _______ studying."',
        options: ['for', 'to', 'with', 'at'],
        correctAnswers: [1],
        explanation: '"Conducive to" means helpful or favorable for.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The politician\'s speech was completely devoid _______ meaning."',
        options: ['from', 'of', 'in', 'with'],
        correctAnswers: [1],
        explanation: '"Devoid of" means completely lacking.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "She is highly proficient _______ several programming languages."',
        options: ['in', 'at', 'with', 'on'],
        correctAnswers: [0],
        explanation: '"Proficient in" means skilled or expert in.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He is completely obsessed _______ winning the competition."',
        options: ['by', 'with', 'for', 'on'],
        correctAnswers: [1],
        explanation: '"Obsessed with" means excessively preoccupied with.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The new regulations are completely disproportionate _______ the actual risk."',
        options: ['with', 'to', 'for', 'from'],
        correctAnswers: [1],
        explanation: '"Disproportionate to" means out of proportion with.',
      },
    ],
    audioContent: [
      { text: 'dependent preposition', type: 'phrase', context: 'Grammar' },
      { text: 'collocation', type: 'word', context: 'Word combination' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 5,
    title: 'Nuanced Vocabulary (Synonym Differentiation)',
    description: 'Choose precise words from similar options.',
    content: {
      introduction: 'Advanced vocabulary requires distinguishing between near-synonyms with subtle differences.',
      objectives: [
        'Distinguish similar words',
        'Choose appropriate synonyms',
        'Understand connotations',
        'Use precise vocabulary'
      ],
      mainContent: 'Near-synonyms: meticulous/fastidious, ubiquitous/omnipresent, nostalgia/reminiscence, compelling/coercive, capricious/volatile.',
      summary: 'You choose precise words that capture exact meanings.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The detective conducted a _______ search of the crime scene."',
        options: ['meticulous', 'fastidious', 'punctilious', 'scrupulous'],
        correctAnswers: [0],
        explanation: '"Meticulous" emphasizes careful attention to detail (most common).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Smartphones have become _______ in modern society."',
        options: ['ubiquitous', 'omnipresent', 'pervasive', 'universal'],
        correctAnswers: [0],
        explanation: '"Ubiquitous" means present everywhere (most natural here).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The smell of fresh bread evoked a feeling of profound _______."',
        options: ['nostalgia', 'reminiscence', 'memory', 'recollection'],
        correctAnswers: [0],
        explanation: '"Nostalgia" captures the sentimental longing for the past.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "His arguments were so _______ that everyone agreed with him."',
        options: ['compelling', 'coercive', 'forceful', 'pushy'],
        correctAnswers: [0],
        explanation: '"Compelling" means convincing and persuasive (positive).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The weather in this region is notoriously _______, changing from sun to rain in minutes."',
        options: ['fickle', 'capricious', 'volatile', 'erratic'],
        correctAnswers: [1],
        explanation: '"Capricious" emphasizes sudden, unpredictable changes.',
      },
    ],
    audioContent: [
      { text: 'synonym', type: 'word', context: 'Vocabulary' },
      { text: 'nuance', type: 'word', context: 'Subtle difference' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 6,
    title: 'Advanced Phrasal Verbs',
    description: 'Master sophisticated multi-word verbs.',
    content: {
      introduction: 'C1-level phrasal verbs express complex meanings in formal and informal contexts.',
      objectives: [
        'Use advanced phrasal verbs',
        'Understand figurative meanings',
        'Distinguish similar phrasal verbs',
        'Apply in appropriate contexts'
      ],
      mainContent: 'Advanced phrasal verbs: fall through, iron out, single out, come in for, drown out.',
      summary: 'You use sophisticated phrasal verbs naturally.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The deal fell _______ at the last minute due to a lack of funding."',
        options: ['apart', 'down', 'through', 'out'],
        correctAnswers: [2],
        explanation: '"Fall through" means to fail or not happen (plans/deals).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "We need to iron _______ a few problems before we launch the product."',
        options: ['out', 'off', 'up', 'away'],
        correctAnswers: [0],
        explanation: '"Iron out" means to resolve or fix problems.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The teacher singled him _______ for his outstanding contribution."',
        options: ['up', 'out', 'off', 'down'],
        correctAnswers: [1],
        explanation: '"Single out" means to select or identify someone specifically.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The government\'s plans have come _______ fierce criticism from the opposition."',
        options: ['up against', 'in for', 'down with', 'out of'],
        correctAnswers: [1],
        explanation: '"Come in for" means to receive (usually criticism).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The noise of the train drowned _______ his words."',
        options: ['out', 'off', 'away', 'down'],
        correctAnswers: [0],
        explanation: '"Drown out" means to make inaudible by being louder.',
      },
    ],
    audioContent: [
      { text: 'phrasal verb', type: 'phrase', context: 'Grammar' },
      { text: 'fall through', type: 'phrase', context: 'Fail to happen' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 7,
    title: 'Idioms and Proverbs',
    description: 'Use idiomatic expressions naturally.',
    content: {
      introduction: 'Idioms and proverbs are fixed expressions with figurative meanings.',
      objectives: [
        'Understand common idioms',
        'Use idioms appropriately',
        'Recognize figurative meanings',
        'Apply idioms in context'
      ],
      mainContent: 'Common idioms: by and large, on the brink of, throw caution to the wind, hit the nail on the head, a far cry from.',
      summary: 'You use idiomatic expressions to sound natural and fluent.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "By and _______, the new system has been a success."',
        options: ['large', 'small', 'all', 'whole'],
        correctAnswers: [0],
        explanation: '"By and large" means generally or overall.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The company is on the _______ of collapse."',
        options: ['brink', 'edge', 'verge', 'point'],
        correctAnswers: [0],
        explanation: '"On the brink of" means very close to (usually something bad).',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He decided to throw caution to the _______ and quit his job."',
        options: ['air', 'wind', 'breeze', 'storm'],
        correctAnswers: [1],
        explanation: '"Throw caution to the wind" means to take a risk.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "You\'ve hit the nail on the _______ with that analysis."',
        options: ['head', 'top', 'point', 'mark'],
        correctAnswers: [0],
        explanation: '"Hit the nail on the head" means to be exactly right.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It\'s a far _______ from the original proposal."',
        options: ['cry', 'shout', 'call', 'distance'],
        correctAnswers: [0],
        explanation: '"A far cry from" means very different from.',
      },
    ],
    audioContent: [
      { text: 'idiom', type: 'word', context: 'Fixed expression' },
      { text: 'by and large', type: 'phrase', context: 'Generally' },
    ],
  },
  {
    levelId: 10,
    lessonNumber: 8,
    title: 'Double Comparatives and Idiomatic Structures',
    description: 'Use correlative structures expressing proportional relationships.',
    content: {
      introduction: 'Double comparatives and special structures express how one thing changes in relation to another.',
      objectives: [
        'Use "the...the" comparatives',
        'Use "no sooner...than" structures',
        'Use "not so much...as" patterns',
        'Apply formal correlative structures'
      ],
      mainContent: 'Patterns: "The more...the better", "No sooner...than", "Not so much...as", "as do/does".',
      summary: 'You use sophisticated correlative structures for complex relationships.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "The more you practice, the _______ you will become."',
        options: ['better', 'best', 'good', 'more better'],
        correctAnswers: [0],
        explanation: '"The more...the + comparative" shows proportional relationship.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "No sooner had I arrived _______ the meeting started."',
        options: ['when', 'then', 'than', 'that'],
        correctAnswers: [2],
        explanation: '"No sooner...than" (inverted structure) means immediately after.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "It\'s not so much a career _______ a calling."',
        options: ['than', 'as', 'like', 'but'],
        correctAnswers: [1],
        explanation: '"Not so much...as" emphasizes the second element.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "He works incredibly hard, as _______ his entire team."',
        options: ['do', 'does', 'is', 'are'],
        correctAnswers: [1],
        explanation: '"As does" (singular subject) creates parallel structure.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete the sentence: "Try as he _______, he couldn\'t open the jar."',
        options: ['might', 'could', 'would', 'should'],
        correctAnswers: [0],
        explanation: '"Try as he might" is an idiomatic structure expressing effort despite inability.',
      },
    ],
    audioContent: [
      { text: 'double comparative', type: 'phrase', context: 'Grammar structure' },
      { text: 'correlative structure', type: 'phrase', context: 'Grammar pattern' },
    ],
  },
];
