// LEVEL 5 - A2/B1 (Upper Elementary)
export const level5Lessons = [
  {
    levelId: 5,
    lessonNumber: 1,
    title: 'Reported Speech',
    description: 'Learn to convert direct speech to reported speech.',
    content: {
      introduction: 'Reported speech allows us to share what others said without using direct quotes.',
      objectives: ['Convert direct to reported speech', 'Use reporting verbs correctly', 'Understand tense shifts in reported speech'],
      mainContent: 'Key structures: He said (that) he was tired. She told me she would come. Changes: present → past, will → would.',
      summary: 'You can now report what others have said correctly.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Convert to reported speech: "I am busy." → "He said that he _______."',
        options: ['am busy', 'was busy', 'is busy', 'been busy'],
        correctAnswers: [1],
        explanation: 'Present tense becomes past in reported speech.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "She told me that she _______ come to the party."',
        options: ['will', 'would', 'is', 'are'],
        correctAnswers: [1],
        explanation: '"would" is used in reported speech when the original was "will".',
      },
      {
        type: 'listening',
        question: 'Listen: "They said they had finished the project." Which reporting verb is used?',
        audioPrompt: 'said',
        options: ['told', 'said', 'asked', 'explained'],
        correctAnswers: [1],
        explanation: '"said" is used with "that" clause.',
      },
      {
        type: 'multiple-choice',
        question: 'Convert: "Do you like pizza?" (she asked) → "She asked if I _______."',
        options: ['like', 'liked', 'likes', 'would like'],
        correctAnswers: [1],
        explanation: 'Questions in reported speech use past tense.',
      },
      {
        type: 'listening',
        question: 'Complete: "He told me that he _______ to study harder."',
        audioPrompt: 'was going',
        options: ['will go', 'is going', 'was going', 'goes'],
        correctAnswers: [2],
        explanation: 'Present continuous becomes past continuous in reported speech.',
      },
    ],
    audioContent: [
      { text: 'said', type: 'word', context: 'Reporting verb' },
      { text: 'told', type: 'word', context: 'Reporting verb' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 2,
    title: 'Conditional Statements',
    description: 'Master if-clauses and conditional structures.',
    content: {
      introduction: 'Conditionals express possible situations and their results.',
      objectives: ['Use first conditional correctly', 'Use second conditional for hypothetical situations', 'Understand mixed conditionals'],
      mainContent: 'First conditional: If + present, will + infinitive. Second conditional: If + past, would + infinitive.',
      summary: 'You understand and can use all three conditional types.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete: "If you study hard, you _______ the exam."',
        options: ['will pass', 'would pass', 'pass', 'passed'],
        correctAnswers: [0],
        explanation: 'First conditional uses will + infinitive for likely future events.',
      },
      {
        type: 'listening',
        question: 'Complete: "If I were rich, I _______ travel around the world."',
        audioPrompt: 'would',
        options: ['will', 'would', 'am', 'can'],
        correctAnswers: [1],
        explanation: 'Second conditional uses would for hypothetical situations.',
      },
      {
        type: 'multiple-choice',
        question: 'Choose the correct second conditional:',
        options: ['If you will work harder, you would succeed.', 'If you worked harder, you would succeed.', 'If you work harder, you would succeed.', 'If you worked, you will succeed.'],
        correctAnswers: [1],
        explanation: 'Second conditional needs past tense in the if-clause.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "Unless you pay attention, you _______not understand."',
        options: ['will', 'would', 'do', 'did'],
        correctAnswers: [0],
        explanation: '"Unless" works like first conditional: will + infinitive.',
      },
      {
        type: 'listening',
        question: 'What does this sentence express? "If you had studied, you would have passed."',
        audioPrompt: 'past unreal situation',
        options: ['A future possibility', 'A likely future event', 'A past unreal situation', 'A present wish'],
        correctAnswers: [2],
        explanation: 'Third conditional discusses past situations that did not happen.',
      },
    ],
    audioContent: [
      { text: 'conditional', type: 'word', context: 'Grammar concept' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 3,
    title: 'Phrasal Verbs',
    description: 'Learn common phrasal verbs and their meanings.',
    content: {
      introduction: 'Phrasal verbs combine a verb with a particle to create new meanings.',
      objectives: ['Understand phrasal verb meanings', 'Use phrasal verbs in context', 'Know separable vs. inseparable phrasal verbs'],
      mainContent: 'Common phrasal verbs: put up with (tolerate), look after (care for), give up (quit), run into (meet by chance).',
      summary: 'You can use phrasal verbs correctly in writing and speech.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What does "put up with" mean?',
        options: ['To construct', 'To tolerate', 'To install', 'To increase'],
        correctAnswers: [1],
        explanation: '"Put up with" means to tolerate or accept something unpleasant.',
      },
      {
        type: 'listening',
        question: 'Complete: "I have to _______ my younger siblings while my parents are out."',
        audioPrompt: 'look after',
        options: ['look at', 'look for', 'look after', 'look up'],
        correctAnswers: [2],
        explanation: '"Look after" means to take care of someone.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "She _______ smoking three months ago and feels much healthier."',
        options: ['gave up', 'gave in', 'gave out', 'gave back'],
        correctAnswers: [0],
        explanation: '"Give up" means to stop or quit an activity.',
      },
      {
        type: 'multiple-choice',
        question: 'What happened? "I ran into my old friend at the supermarket."',
        options: ['I collided with my friend', 'I met my friend by chance', 'I hid from my friend', 'I chased my friend'],
        correctAnswers: [1],
        explanation: '"Run into" means to meet someone unexpectedly.',
      },
      {
        type: 'listening',
        question: 'Complete: "I need to _______ a reference from my previous employer."',
        audioPrompt: 'get',
        options: ['get on', 'get off', 'get by', 'get in'],
        correctAnswers: [0],
        explanation: 'Context indicates need for recommendation/reference.',
      },
    ],
    audioContent: [
      { text: 'phrasal verb', type: 'phrase', context: 'Grammar concept' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 4,
    title: 'Complex Sentences',
    description: 'Master complex sentence structures with multiple clauses.',
    content: {
      introduction: 'Complex sentences combine independent and dependent clauses.',
      objectives: ['Use subordinating conjunctions correctly', 'Create complex sentences', 'Understand clause relationships'],
      mainContent: 'Subordinating conjunctions: because, although, while, when, unless, if. Patterns: Main clause + subordinate clause.',
      summary: 'You can write complex sentences with proper clause relationships.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete with correct conjunction: "_______ he was tired, he continued working."',
        options: ['Because', 'Although', 'If', 'Since'],
        correctAnswers: [1],
        explanation: '"Although" shows contrast between two ideas.',
      },
      {
        type: 'listening',
        question: 'Which sentence is correct?',
        audioPrompt: 'correct answer',
        options: ['When I arrive home, I will call you.', 'When I will arrive home, I call you.', 'When I arrived home, I call you.', 'When I arrive home, I called you.'],
        correctAnswers: [0],
        explanation: 'Time clause uses present tense; main clause uses will.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "She could not find her keys _______ she looked everywhere."',
        options: ['although', 'if', 'unless', 'because'],
        correctAnswers: [0],
        explanation: '"Although" expresses contrast: she looked but did not find them.',
      },
      {
        type: 'multiple-choice',
        question: 'Join these sentences: "He studied hard. He passed the exam."',
        options: ['He studied hard although he passed.', 'Because he studied hard, he passed.', 'Although he studied hard, he passed.', 'He passed unless he studied.'],
        correctAnswers: [1],
        explanation: '"Because" shows cause-and-effect relationship.',
      },
      {
        type: 'listening',
        question: 'Complete: "_______ you finish your homework, you cannot watch TV."',
        audioPrompt: 'Unless',
        options: ['If', 'Unless', 'Although', 'Because'],
        correctAnswers: [1],
        explanation: '"Unless" means "if not" and introduces a condition.',
      },
    ],
    audioContent: [
      { text: 'complex sentence', type: 'phrase', context: 'Grammar concept' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 5,
    title: 'Future Plans and Intentions',
    description: 'Discuss future plans using various structures.',
    content: {
      introduction: 'Different ways to express future intentions and plans.',
      objectives: ['Use "going to" vs "will" correctly', 'Express intentions with present continuous', 'Discuss fixed future plans'],
      mainContent: '"Going to" for planned future. "Will" for decisions made at moment of speaking. Present continuous for fixed arrangements.',
      summary: 'You can express future plans clearly with appropriate structures.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Which sentence expresses a fixed plan made earlier?',
        options: ['I will go to Paris.', 'I am going to Paris next month.', 'I go to Paris.', 'I am going to go to Paris.'],
        correctAnswers: [1],
        explanation: '"Am going" with specific time shows a planned arrangement.',
      },
      {
        type: 'listening',
        question: 'Complete: "I have already decided. I _______ study medicine."',
        audioPrompt: 'am going to',
        options: ['will', 'am going to', 'am', 'go'],
        correctAnswers: [1],
        explanation: '"Am going to" expresses a previously made decision.',
      },
      {
        type: 'multiple-choice',
        question: 'What does "Are you doing anything tomorrow?" "Yes, I am meeting Sarah."',
        options: ['Distant future intention', 'Fixed arrangement for tomorrow', 'Spontaneous decision', 'Habitual action'],
        correctAnswers: [1],
        explanation: 'Present continuous expresses fixed arrangements.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "A: What are your plans? B: _______ travel to Italy."',
        options: ['I will', 'I am going to', 'I am', 'I have'],
        correctAnswers: [1],
        explanation: '"Going to" is appropriate for stating plans.',
      },
      {
        type: 'listening',
        question: 'Complete: "The train _______ at 8 PM." (this is the schedule)',
        audioPrompt: 'leaves',
        options: ['is leaving', 'will leave', 'leaves', 'is going to leave'],
        correctAnswers: [2],
        explanation: 'Present simple is used for scheduled events and timetables.',
      },
    ],
    audioContent: [
      { text: 'future plans', type: 'phrase', context: 'Communication' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 6,
    title: 'Opinions and Arguments',
    description: 'Express and defend opinions effectively.',
    content: {
      introduction: 'Learn useful expressions for stating, supporting, and defending opinions.',
      objectives: ['State opinions clearly', 'Support opinions with reasons', 'Respond to different viewpoints'],
      mainContent: 'Phrases: "In my opinion...", "I believe that...", "I would argue that...", "The point is...", "On the other hand...".',
      summary: 'You can express opinions and engage in respectful debate.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'How do you politely introduce your opinion?',
        options: ['You are wrong.', 'In my opinion, climate change is real.', 'Everyone knows that...', 'Obviously...'],
        correctAnswers: [1],
        explanation: '"In my opinion" is a polite way to state a viewpoint.',
      },
      {
        type: 'listening',
        question: 'Complete: "I _______ that technology has improved our lives."',
        audioPrompt: 'believe',
        options: ['argue', 'believe', 'claim', 'say'],
        correctAnswers: [1],
        explanation: '"Believe" is appropriate for expressing personal opinions.',
      },
      {
        type: 'multiple-choice',
        question: 'How do you introduce a contrasting viewpoint?',
        options: ['Furthermore...', 'On the other hand...', 'In addition...', 'Similarly...'],
        correctAnswers: [1],
        explanation: '"On the other hand" introduces a different perspective.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "The main point is that _______ should have equal rights."',
        options: ['peoples', 'people', 'peoples\'', 'peopless'],
        correctAnswers: [1],
        explanation: '"People" is the correct plural form.',
      },
      {
        type: 'listening',
        question: 'Complete: "I would _______ that social media has negative effects too."',
        audioPrompt: 'argue',
        options: ['argue', 'claim', 'say', 'tell'],
        correctAnswers: [0],
        explanation: '"Argue" suggests providing reasons for a position.',
      },
    ],
    audioContent: [
      { text: 'opinion', type: 'word', context: 'Communication' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 7,
    title: 'Storytelling Techniques',
    description: 'Use narrative techniques to tell engaging stories.',
    content: {
      introduction: 'Learn to structure stories with interesting details and proper sequencing.',
      objectives: ['Use past tenses for narrative', 'Use sequencing words', 'Add descriptive details to stories'],
      mainContent: 'Sequencing: Once, Then, After that, Eventually, Finally. Details with descriptive adjectives and adverbs. Mix of past simple and past continuous.',
      summary: 'You can tell engaging, well-structured stories in English.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Which sequence word comes first in a narrative?',
        options: ['Then', 'Once', 'Finally', 'After that'],
        correctAnswers: [1],
        explanation: '"Once" is used to set the initial scene of a story.',
      },
      {
        type: 'listening',
        question: 'Complete the narrative: "Once I arrived, I _______ everyone enjoying themselves."',
        audioPrompt: 'saw',
        options: ['see', 'saw', 'was seeing', 'have seen'],
        correctAnswers: [1],
        explanation: 'Past simple narrates the main events.',
      },
      {
        type: 'multiple-choice',
        question: 'Combine: "I was walking. I saw a beautiful bird."',
        options: ['I walked and saw a beautiful bird.', 'While I was walking, I saw a beautiful bird.', 'I was walking when I see a beautiful bird.', 'Walking, I was seeing a beautiful bird.'],
        correctAnswers: [1],
        explanation: 'Past continuous + past simple shows action interrupted by event.',
      },
      {
        type: 'multiple-choice',
        question: 'Which word best continues: "After I finished my coffee, I _______."',
        options: ['am leaving', 'will leave', 'left', 'have left'],
        correctAnswers: [2],
        explanation: 'After + past simple requires past simple in main clause.',
      },
      {
        type: 'listening',
        question: 'Complete: "Eventually, I _______ that it was all a misunderstanding."',
        audioPrompt: 'realized',
        options: ['realized', 'realize', 'am realizing', 'have realized'],
        correctAnswers: [0],
        explanation: 'Past simple ends narrative sequences.',
      },
    ],
    audioContent: [
      { text: 'narrative', type: 'word', context: 'Story technique' },
    ],
  },
  {
    levelId: 5,
    lessonNumber: 8,
    title: 'Problem Solving',
    description: 'Discuss problems and propose solutions.',
    content: {
      introduction: 'Learn vocabulary and structures for identifying and solving problems.',
      objectives: ['Describe problems clearly', 'Propose multiple solutions', 'Evaluate solutions', 'Reach agreements'],
      mainContent: 'Problem phrases: "The issue is...", "The main problem is...". Solution phrases: "We could...", "One solution would be...", "We might...".',
      summary: 'You can discuss problems and collaborate on solutions effectively.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete: "The main problem is that _______."',
        options: ['we have no idea', 'nobody knows nothing', 'we don\'t have enough information', 'people are not knowing'],
        correctAnswers: [2],
        explanation: 'Use correct grammatical structure to state problems.',
      },
      {
        type: 'listening',
        question: 'How do you politely suggest a solution?',
        audioPrompt: 'We could',
        options: ['You must do this.', 'We could try a different approach.', 'Do this immediately.', 'It is the only way.'],
        correctAnswers: [1],
        explanation: '"We could" offers a tentative suggestion.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "One solution would be to _______."',
        options: ['increase the budget', 'would increase', 'increasing', 'have increased'],
        correctAnswers: [0],
        explanation: 'Use infinitive after "would be to".',
      },
      {
        type: 'multiple-choice',
        question: 'How do you evaluate a proposed solution?',
        options: ['That is stupid.', 'That solution might work, but we need to consider...', 'Never.', 'It won\'t work.'],
        correctAnswers: [1],
        explanation: 'Respectfully evaluate while considering other factors.',
      },
      {
        type: 'listening',
        question: 'Complete: "Do you agree that we should _______?"',
        audioPrompt: 'take a different approach',
        options: ['has taken', 'to take', 'take', 'taken'],
        correctAnswers: [2],
        explanation: 'Use base form after "should".',
      },
    ],
    audioContent: [
      { text: 'solution', type: 'word', context: 'Problem-solving' },
    ],
  },
];

// LEVEL 6 - B1 (Intermediate)
export const level6Lessons = [
  {
    levelId: 6,
    lessonNumber: 1,
    title: 'Continuous Tenses',
    description: 'Master all continuous tenses for ongoing actions.',
    content: {
      introduction: 'Continuous tenses describe actions in progress or repeated activities.',
      objectives: ['Use present continuous', 'Use past continuous', 'Use future continuous', 'Use present perfect continuous'],
      mainContent: 'Present continuous: is + -ing. Past continuous: was + -ing. Future continuous: will be + -ing. Present perfect continuous: has been + -ing.',
      summary: 'You can use all continuous tenses appropriately.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete: "Right now, she _______ on an important project."',
        options: ['works', 'is working', 'has worked', 'worked'],
        correctAnswers: [1],
        explanation: 'Present continuous describes action happening now.',
      },
      {
        type: 'listening',
        question: 'What was he doing when the phone rang?',
        audioPrompt: 'was cooking',
        options: ['cooks', 'is cooking', 'was cooking', 'has cooked'],
        correctAnswers: [2],
        explanation: 'Past continuous describes interrupted past action.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "By next week, I _______ for three months."',
        options: ['will have studied', 'will be studying', 'study', 'have studied'],
        correctAnswers: [1],
        explanation: 'Future continuous describes ongoing future action.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "She _______ there for years and has extensive experience."',
        options: ['is working', 'has been working', 'works', 'worked'],
        correctAnswers: [1],
        explanation: 'Present perfect continuous shows duration up to present.',
      },
      {
        type: 'listening',
        question: 'What tense? "They have been negotiating for hours."',
        audioPrompt: 'present perfect continuous',
        options: ['Present continuous', 'Past continuous', 'Present perfect continuous', 'Future continuous'],
        correctAnswers: [2],
        explanation: '"Have been negotiating" is present perfect continuous.',
      },
    ],
    audioContent: [
      { text: 'continuous', type: 'word', context: 'Tense' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 2,
    title: 'Advanced Modals',
    description: 'Use modal verbs to express possibility, obligation, and deduction.',
    content: {
      introduction: 'Advanced modals express subtle meanings about possibility and probability.',
      objectives: ['Use modals for speculation', 'Use modals for obligation and permission', 'Understand modal nuances'],
      mainContent: 'Possibility: might, could, may. Obligation: must, have to, should. Deduction: must, can\'t, must have.',
      summary: 'You use modals to express complex ideas precisely.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete: "He _______ be at home. I am not sure."',
        options: ['must', 'might', 'will', 'is'],
        correctAnswers: [1],
        explanation: '"Might" expresses uncertainty about present situation.',
      },
      {
        type: 'listening',
        question: 'What can you deduce? "She _______ the exam. She studied so hard."',
        audioPrompt: 'must have passed',
        options: ['might pass', 'must have passed', 'could pass', 'should pass'],
        correctAnswers: [1],
        explanation: '"Must have passed" deduces certain past conclusion.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "You _______ tell anyone. It is a secret."',
        options: ['must not', 'don\'t have to', 'don\'t need to', 'can\'t'],
        correctAnswers: [0],
        explanation: '"Must not" expresses prohibition.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "He _______ attend the meeting, but it would be good if he did."',
        options: ['must', 'has to', 'doesn\'t have to', 'should'],
        correctAnswers: [2],
        explanation: '"Doesn\'t have to" means no obligation.',
      },
      {
        type: 'listening',
        question: 'Complete: "She _______ be lying. I saw her there yesterday."',
        audioPrompt: 'can\'t',
        options: ['might', 'could', 'can\'t', 'must'],
        correctAnswers: [2],
        explanation: '"Can\'t" expresses certainty that something is impossible.',
      },
    ],
    audioContent: [
      { text: 'modal verb', type: 'phrase', context: 'Grammar' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 3,
    title: 'Passive Voice Advanced',
    description: 'Use passive voice in complex and formal contexts.',
    content: {
      introduction: 'Passive voice emphasizes the action rather than the doer.',
      objectives: ['Form passive voice in various tenses', 'Use passive in formal writing', 'Understand when to use passive'],
      mainContent: 'Passive with different tenses. Passives with modals: must be done, should have been done. By phrase for agent.',
      summary: 'You use passive voice effectively in formal and academic writing.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Convert to passive: "They are building a new hospital."',
        options: ['A new hospital is built.', 'A new hospital is being built.', 'A new hospital was being built.', 'A new hospital will be built.'],
        correctAnswers: [1],
        explanation: 'Present continuous becomes present continuous passive.',
      },
      {
        type: 'listening',
        question: 'Complete passive: "The report _______ by tomorrow."',
        audioPrompt: 'must be finished',
        options: ['must finish', 'must be finished', 'must have finished', 'should finish'],
        correctAnswers: [1],
        explanation: 'Modal + passive: must + be + past participle.',
      },
      {
        type: 'multiple-choice',
        question: 'Convert: "Shakespeare wrote Hamlet." → "Hamlet _______."',
        options: ['was written', 'was written by Shakespeare', 'has been written', 'is written'],
        correctAnswers: [1],
        explanation: 'Include agent with "by" for important information.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "The letter _______ deliver by the postal service."',
        options: ['will be', 'is being', 'has been', 'was'],
        correctAnswers: [0],
        explanation: 'Future passive: will + be + past participle.',
      },
      {
        type: 'listening',
        question: 'Complete: "The funds _______ been allocated to research projects."',
        audioPrompt: 'have',
        options: ['have', 'has', 'was', 'is'],
        correctAnswers: [0],
        explanation: 'Present perfect passive: have + been + past participle.',
      },
    ],
    audioContent: [
      { text: 'passive voice', type: 'phrase', context: 'Grammar' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 4,
    title: 'Subjunctive Mood',
    description: 'Express wishes, suggestions, and unreal situations.',
    content: {
      introduction: 'The subjunctive mood expresses wishes, demands, and contrary-to-fact situations.',
      objectives: ['Use subjunctive in formal suggestions', 'Express wishes with subjunctive', 'Understand subjunctive forms'],
      mainContent: '"I suggest that he be involved." "I wish he were here." Forms: were (not was), base form after suggest/demand.',
      summary: 'You use subjunctive mood in formal and literary contexts.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Complete formal suggestion: "I suggest that she _______ her manager."',
        options: ['talks to', 'talk to', 'talked to', 'will talk to'],
        correctAnswers: [1],
        explanation: 'After "suggest" use base form (subjunctive).',
      },
      {
        type: 'listening',
        question: 'Complete wish: "I wish I _______ there with you."',
        audioPrompt: 'were',
        options: ['was', 'were', 'am', 'have been'],
        correctAnswers: [1],
        explanation: 'Use "were" in subjunctive wishes, even with "I".',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "The principal insisted that the student _______ an apology."',
        options: ['makes', 'make', 'making', 'made'],
        correctAnswers: [1],
        explanation: 'After "insisted" use base form subjunctive.',
      },
      {
        type: 'multiple-choice',
        question: 'Which is correct? (expressing unreal situation)',
        options: ['If I was you, I would leave.', 'If I were you, I would leave.', 'If I am you, I leave.', 'If I will be you, I would leave.'],
        correctAnswers: [1],
        explanation: 'Use "were" in unreal conditional (subjunctive).',
      },
      {
        type: 'listening',
        question: 'Complete: "It is important that every student _______ their best."',
        audioPrompt: 'do',
        options: ['does', 'do', 'doing', 'did'],
        correctAnswers: [1],
        explanation: 'Use base form after importance statements (subjunctive).',
      },
    ],
    audioContent: [
      { text: 'subjunctive', type: 'word', context: 'Mood' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 5,
    title: 'Business Communication',
    description: 'Communicate professionally in business contexts.',
    content: {
      introduction: 'Master formal language and professional etiquette in business English.',
      objectives: ['Write professional emails', 'Use formal register', 'Conduct professional conversations', 'Negotiate professionally'],
      mainContent: 'Email structures: greeting, purpose, details, closing. Formal phrases: "I would like to inquire...", "Could you kindly...", "Please find attached...".',
      summary: 'You communicate effectively in professional business settings.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'How do you begin a professional email to someone you do not know?',
        options: ['Hey there!', 'Dear Sir/Madam,', 'Hi!', 'Yo!'],
        correctAnswers: [1],
        explanation: '"Dear Sir/Madam," is the formal professional greeting.',
      },
      {
        type: 'listening',
        question: 'Complete professionally: "I would _______ to schedule a meeting."',
        audioPrompt: 'like',
        options: ['want', 'like', 'love', 'wish'],
        correctAnswers: [1],
        explanation: '"Would like" is formal professional language.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "Could you kindly _______ the report by Friday?"',
        options: ['send', 'sending', 'sent', 'have sent'],
        correctAnswers: [0],
        explanation: 'Use base form after "Could you kindly".',
      },
      {
        type: 'multiple-choice',
        question: 'How do you close a professional email?',
        options: ['See you!', 'Bye!', 'Yours sincerely,', 'Peace out!'],
        correctAnswers: [2],
        explanation: '"Yours sincerely," is a formal closing.',
      },
      {
        type: 'listening',
        question: 'Complete: "Please find _______ the required documents."',
        audioPrompt: 'attached',
        options: ['attached', 'attach', 'attaching', 'attached with'],
        correctAnswers: [0],
        explanation: '"Please find attached" is standard professional phrase.',
      },
    ],
    audioContent: [
      { text: 'business communication', type: 'phrase', context: 'Professional' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 6,
    title: 'Debating Skills',
    description: 'Engage in structured debates and arguments.',
    content: {
      introduction: 'Learn to argue both sides of an issue and persuade listeners.',
      objectives: ['Present arguments clearly', 'Use evidence and examples', 'Refute opposing views', 'Reach conclusions'],
      mainContent: 'Argument markers: First, Second, Furthermore, However, In contrast. Persuasion: "This demonstrates that...", "The evidence suggests...".',
      summary: 'You debate effectively using logical arguments and evidence.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'How do you start your first argument?',
        options: ['Obviously...', 'First of all, I believe...', 'Clearly...', 'As everyone knows...'],
        correctAnswers: [1],
        explanation: '"First of all" appropriately introduces first argument.',
      },
      {
        type: 'listening',
        question: 'Complete: "The evidence _______ that climate change is real."',
        audioPrompt: 'suggests',
        options: ['proves', 'suggests', 'shows', 'demonstrates'],
        correctAnswers: [1],
        explanation: '"Suggests" appropriately presents research findings.',
      },
      {
        type: 'multiple-choice',
        question: 'How do you respond to opposing view?',
        options: ['You are wrong.', 'While that is a valid point, I would argue...', 'That is stupid.', 'Everyone disagrees.'],
        correctAnswers: [1],
        explanation: 'Acknowledge opposing view respectfully before refuting.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "In conclusion, the data clearly _______ that reform is needed."',
        options: ['suggests', 'indicates', 'shows', 'demonstrates'],
        correctAnswers: [2],
        explanation: '"Demonstrates" is strong for conclusions.',
      },
      {
        type: 'listening',
        question: 'Complete: "Furthermore, we should _______ that economic benefits outweigh costs."',
        audioPrompt: 'consider',
        options: ['consider', 'think', 'remember', 'note'],
        correctAnswers: [0],
        explanation: '"Consider" invites reflection on additional points.',
      },
    ],
    audioContent: [
      { text: 'debate', type: 'word', context: 'Argumentation' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 7,
    title: 'Literature and Arts',
    description: 'Discuss literature, film, and artistic works.',
    content: {
      introduction: 'Learn vocabulary and expressions for discussing creative works.',
      objectives: ['Analyze literary works', 'Discuss themes and symbolism', 'Express appreciation and criticism', 'Understand artistic techniques'],
      mainContent: 'Techniques: metaphor, symbolism, foreshadowing, irony. Analysis words: protagonist, plot, narrative, characterization.',
      summary: 'You discuss literature and arts with sophisticated language.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is symbolism in literature?',
        options: ['Using similar words', 'Using objects to represent ideas', 'Making rhymes', 'Using exaggeration'],
        correctAnswers: [1],
        explanation: 'Symbolism uses objects/colors to represent abstract ideas.',
      },
      {
        type: 'listening',
        question: 'Complete: "The author\'s use of _______ contrasts hope with despair."',
        audioPrompt: 'metaphor',
        options: ['rhyme', 'metaphor', 'setting', 'dialogue'],
        correctAnswers: [1],
        explanation: 'Metaphors create comparisons between ideas.',
      },
      {
        type: 'multiple-choice',
        question: 'What does "foreshadowing" mean in a story?',
        options: ['Ending the story', 'Hinting at future events', 'Describing past events', 'Repeating information'],
        correctAnswers: [1],
        explanation: 'Foreshadowing hints at events coming later.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "The film brilliantly _______ the protagonist\'s internal conflict."',
        options: ['shows', 'depicts', 'portrays', 'demonstrates'],
        correctAnswers: [2],
        explanation: '"Portrays" appropriately describes artistic representation.',
      },
      {
        type: 'listening',
        question: 'What does "irony" mean?',
        audioPrompt: 'opposite of expected',
        options: ['Being funny', 'Using opposite of expected meaning', 'Being sarcastic', 'Making jokes'],
        correctAnswers: [1],
        explanation: 'Irony contrasts expectation with reality.',
      },
    ],
    audioContent: [
      { text: 'literature', type: 'word', context: 'Arts' },
      { text: 'symbolism', type: 'word', context: 'Literary device' },
    ],
  },
  {
    levelId: 6,
    lessonNumber: 8,
    title: 'Environmental Issues',
    description: 'Discuss environmental concerns and solutions.',
    content: {
      introduction: 'Learn vocabulary and structures for discussing environmental topics.',
      objectives: ['Discuss environmental problems', 'Propose sustainable solutions', 'Understand environmental terminology', 'Express environmental concerns'],
      mainContent: 'Terms: sustainability, carbon footprint, conservation, renewable energy, biodiversity, ecosystem.',
      summary: 'You discuss environmental issues with appropriate terminology.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is a "carbon footprint"?',
        options: ['A mark left by feet', 'Measure of environmental impact', 'A type of shoe', 'A scientific measurement'],
        correctAnswers: [1],
        explanation: 'Carbon footprint measures environmental impact of activities.',
      },
      {
        type: 'listening',
        question: 'Complete: "We must promote _______ energy sources."',
        audioPrompt: 'renewable',
        options: ['resources', 'renewable', 'recycled', 'sustainable'],
        correctAnswers: [1],
        explanation: '"Renewable" refers to energy sources that regenerate.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "Protecting _______ is essential for wildlife survival."',
        options: ['surroundings', 'ecosystems', 'weather', 'countries'],
        correctAnswers: [1],
        explanation: 'Ecosystems are interconnected systems where organisms live.',
      },
      {
        type: 'multiple-choice',
        question: 'What does "conservation" mean?',
        options: ['Discussing politics', 'Protecting and preserving', 'Changing nature', 'Building structures'],
        correctAnswers: [1],
        explanation: 'Conservation means protecting and preserving natural resources.',
      },
      {
        type: 'listening',
        question: 'Complete: "_______ of habitats threatens many species."',
        audioPrompt: 'Loss',
        options: ['Finding', 'Loss', 'Discovery', 'Creation'],
        correctAnswers: [1],
        explanation: 'Loss of habitat is a major environmental concern.',
      },
    ],
    audioContent: [
      { text: 'environment', type: 'word', context: 'Environmental studies' },
      { text: 'sustainability', type: 'word', context: 'Environmental concept' },
    ],
  },
];

// LEVEL 7 - B1/B2 (Upper Intermediate)
export const level7Lessons = [
  {
    levelId: 7,
    lessonNumber: 1,
    title: 'Academic Writing',
    description: 'Master formal academic writing conventions.',
    content: {
      introduction: 'Learn structures and language for academic essays and papers.',
      objectives: ['Structure academic arguments', 'Use citations properly', 'Write formal paragraphs', 'Develop thesis statements'],
      mainContent: 'Structure: Introduction, Body paragraphs, Conclusion. Topic sentences, supporting evidence, transitions, paraphrasing.',
      summary: 'You write well-structured academic essays using formal conventions.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is a thesis statement?',
        options: ['The title of your essay', 'Your main argument', 'A quote you use', 'A conclusion paragraph'],
        correctAnswers: [1],
        explanation: 'A thesis statement presents your main argument.',
      },
      {
        type: 'listening',
        question: 'How should you support arguments in academic writing?',
        audioPrompt: 'with evidence',
        options: ['With opinions', 'With evidence and examples', 'With stories', 'Without support'],
        correctAnswers: [1],
        explanation: 'Academic writing requires evidence-based arguments.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete transition: "Furthermore, the research _______ these findings."',
        options: ['contradicts', 'disputes', 'reinforces', 'ignores'],
        correctAnswers: [2],
        explanation: '"Reinforces" means strengthens/supports.',
      },
      {
        type: 'multiple-choice',
        question: 'What is proper paraphrasing?',
        options: ['Copying exact text', 'Restating ideas in different words with citation', 'Using quotation marks', 'Ignoring the source'],
        correctAnswers: [1],
        explanation: 'Paraphrase with proper citation gives credit.',
      },
      {
        type: 'listening',
        question: 'Complete academically: "The data _______ that policy reform is necessary."',
        audioPrompt: 'indicates',
        options: ['shows', 'indicates', 'means', 'tells'],
        correctAnswers: [1],
        explanation: '"Indicates" is appropriately formal for academic writing.',
      },
    ],
    audioContent: [
      { text: 'academic writing', type: 'phrase', context: 'Writing style' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 2,
    title: 'Formal vs. Informal Register',
    description: 'Master stylistic choices for different contexts.',
    content: {
      introduction: 'Choose appropriate language based on audience and context.',
      objectives: ['Recognize register differences', 'Adapt language appropriately', 'Use formal structures', 'Use informal expressions appropriately'],
      mainContent: 'Formal: contractions avoided, complex sentences, passive voice. Informal: contractions used, simple sentences, active voice.',
      summary: 'You adjust your language appropriately for any context.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'Which is formal?',
        options: ['Gonna attend', 'I will be attending', 'Gonna be there', 'Will attend the event'],
        correctAnswers: [1],
        explanation: 'Formal uses "will be attending" not "gonna".',
      },
      {
        type: 'listening',
        question: 'Complete informally: "I _______ down at the beach."',
        audioPrompt: 'hung out',
        options: ['spent time', 'socialized', 'hung out', 'spent leisure hours'],
        correctAnswers: [2],
        explanation: '"Hung out" is casual/informal.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete formally: "We must _______ the proposed legislation."',
        options: ['think about', 'consider', 'check out', 'examine'],
        correctAnswers: [1],
        explanation: '"Consider" is appropriately formal.',
      },
      {
        type: 'multiple-choice',
        question: 'Convert to informal: "I was not able to attend."',
        options: ['I could not attend.', 'I wasn\'t able to attend.', 'I couldn\'t make it.', 'I am unable.'],
        correctAnswers: [2],
        explanation: '"Couldn\'t make it" is casual/informal.',
      },
      {
        type: 'listening',
        question: 'Which uses passive voice (more formal)?',
        audioPrompt: 'The report was submitted',
        options: ['She submitted the report.', 'The report was submitted.', 'She turned in her report.', 'The report was given.'],
        correctAnswers: [1],
        explanation: 'Passive voice is more formal.',
      },
    ],
    audioContent: [
      { text: 'register', type: 'word', context: 'Language style' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 3,
    title: 'Euphemisms and Indirect Speech',
    description: 'Communicate sensitive topics diplomatically.',
    content: {
      introduction: 'Learn tactful language for difficult or delicate situations.',
      objectives: ['Understand euphemisms', 'Use indirect speech', 'Communicate tactfully', 'Understand cultural sensitivities'],
      mainContent: 'Euphemisms soften harsh realities. "Passed away" instead of "died". Indirect speech: "I wonder if you could...".',
      summary: 'You communicate sensitively in delicate situations.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is a euphemism?',
        options: ['A loud noise', 'A mild word for something harsh', 'A musical note', 'A type of flower'],
        correctAnswers: [1],
        explanation: 'Euphemism uses mild language for unpleasant topics.',
      },
      {
        type: 'listening',
        question: 'Which is a euphemism?',
        audioPrompt: 'Passed away',
        options: ['Died', 'Passed away', 'Died suddenly', 'Ceased living'],
        correctAnswers: [1],
        explanation: '"Passed away" is a gentle euphemism.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete indirectly: "I _______ if you might reconsider."',
        options: ['demand', 'wonder', 'insist', 'require'],
        correctAnswers: [1],
        explanation: '"Wonder if" is politely indirect.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete diplomatically: "Perhaps we could _______ this later."',
        options: ['ignore', 'forget', 'revisit', 'drop'],
        correctAnswers: [2],
        explanation: '"Revisit" is diplomatic for reopening discussion.',
      },
      {
        type: 'listening',
        question: 'What does "letting go" euphemistically mean?',
        audioPrompt: 'terminating employment',
        options: ['Releasing', 'Firing/Terminating employment', 'Forgiving', 'Departing'],
        correctAnswers: [1],
        explanation: '"Letting go" euphemistically describes job termination.',
      },
    ],
    audioContent: [
      { text: 'euphemism', type: 'word', context: 'Language device' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 4,
    title: 'Complex Narratives',
    description: 'Craft sophisticated stories with multiple layers.',
    content: {
      introduction: 'Create nuanced narratives with themes, symbolism, and character development.',
      objectives: ['Develop complex characters', 'Use multiple plot levels', 'Employ literary devices', 'Create thematic depth'],
      mainContent: 'Multi-plot structures, character arcs, symbolism, foreshadowing, themes explored through action and dialogue.',
      summary: 'You tell sophisticated, multilayered stories.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What creates character depth?',
        options: ['Describing appearance', 'Showing growth and contradiction', 'Using difficult words', 'Repeating information'],
        correctAnswers: [1],
        explanation: 'Growth and contradictions make characters realistic.',
      },
      {
        type: 'listening',
        question: 'Complete: "The protagonist\'s journey _______ her beliefs about trust."',
        audioPrompt: 'transformed',
        options: ['changed', 'transformed', 'modified', 'revised'],
        correctAnswers: [1],
        explanation: '"Transformed" suggests deep character change.',
      },
      {
        type: 'multiple-choice',
        question: 'What is a subplot?',
        options: ['A small town', 'A secondary plot running parallel to main plot', 'A bad plan', 'A mistake'],
        correctAnswers: [1],
        explanation: 'Subplots enrich main narrative.',
      },
      {
        type: 'multiple-choice',
        question: 'How do symbolism add meaning?',
        options: ['Making text longer', 'Representing ideas through objects', 'Confusing readers', 'Creating problems'],
        correctAnswers: [1],
        explanation: 'Symbols layer meaning into narratives.',
      },
      {
        type: 'listening',
        question: 'Complete: "The narrative _______ several interconnected stories."',
        audioPrompt: 'weaves together',
        options: ['combines', 'weaves together', 'joins', 'puts'],
        correctAnswers: [1],
        explanation: '"Weaves together" elegantly describes narrative structure.',
      },
    ],
    audioContent: [
      { text: 'narrative', type: 'word', context: 'Storytelling' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 5,
    title: 'Professional Scenarios',
    description: 'Navigate complex professional situations.',
    content: {
      introduction: 'Handle advanced professional communication and negotiation.',
      objectives: ['Handle negotiations', 'Manage conflicts diplomatically', 'Present complex ideas', 'Build professional relationships'],
      mainContent: 'Negotiation tactics, conflict resolution, persuasion strategies, relationship building in business contexts.',
      summary: 'You excel in sophisticated professional interactions.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'How do you open a negotiation professionally?',
        options: ['I need this now.', 'I believe we can find a mutually beneficial solution.', 'My way or no way.', 'Take it or leave it.'],
        correctAnswers: [1],
        explanation: 'Seeking mutual benefit creates productive negotiation.',
      },
      {
        type: 'listening',
        question: 'Complete diplomatically: "While I understand your perspective, I _______ propose..."',
        audioPrompt: 'would',
        options: ['can', 'would', 'must', 'should'],
        correctAnswers: [1],
        explanation: '"Would" offers alternative respectfully.',
      },
      {
        type: 'multiple-choice',
        question: 'How do you handle professional disagreement?',
        options: ['Avoid the person', 'Acknowledge concern, then explain your position', 'Get angry', 'Refuse to talk'],
        correctAnswers: [1],
        explanation: 'Acknowledging concerns builds professional relationships.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "I _______ your concerns and appreciate your input."',
        options: ['hate', 'acknowledge', 'ignore', 'dismiss'],
        correctAnswers: [1],
        explanation: '"Acknowledge" validates others professionally.',
      },
      {
        type: 'listening',
        question: 'Complete professionally: "Perhaps we could _______ another meeting to discuss this further."',
        audioPrompt: 'schedule',
        options: ['have', 'schedule', 'set', 'plan'],
        correctAnswers: [1],
        explanation: '"Schedule" is appropriately formal.',
      },
    ],
    audioContent: [
      { text: 'negotiation', type: 'word', context: 'Business' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 6,
    title: 'Cultural References',
    description: 'Understand and discuss cultural allusions.',
    content: {
      introduction: 'Recognize cultural references and their meanings across contexts.',
      objectives: ['Identify cultural allusions', 'Understand historical references', 'Discuss cultural significance', 'Appreciate cultural diversity'],
      mainContent: 'Common references from literature, history, mythology. Understanding context and implications.',
      summary: 'You understand cultural references across texts and conversations.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What does "Catch-22" reference?',
        options: ['A highway', 'An impossible situation (from Joseph Heller\'s novel)', 'A sports game', 'A location'],
        correctAnswers: [1],
        explanation: '"Catch-22" alludes to a dilemma from the novel.',
      },
      {
        type: 'listening',
        question: 'Complete: "Like Don Quixote, he _______ at windmills."',
        audioPrompt: 'tilted',
        options: ['fought', 'tilted', 'attacked', 'rushed'],
        correctAnswers: [1],
        explanation: '"Tilted at windmills" references Cervantes\' character and futile efforts.',
      },
      {
        type: 'multiple-choice',
        question: 'What cultural reference means a tragic flaw?',
        options: ['Achilles heel', 'Golden opportunity', 'Silver bullet', 'Trojan horse'],
        correctAnswers: [0],
        explanation: '"Achilles heel" references Greek mythology—a fatal weakness.',
      },
      {
        type: 'multiple-choice',
        question: 'What does "Big Brother is watching" reference?',
        options: ['Surveillance in general (from Orwell\'s 1984)', 'A TV show', 'A family situation', 'A film'],
        correctAnswers: [0],
        explanation: 'References Orwell\'s totalitarian surveillance concept.',
      },
      {
        type: 'listening',
        question: 'Complete: "This is her _______ moment." (cultural sports reference)',
        audioPrompt: 'Cinderella',
        options: ['princess', 'fairy tale', 'Cinderella', 'victory'],
        correctAnswers: [2],
        explanation: '"Cinderella moment" references surprising underdog success.',
      },
    ],
    audioContent: [
      { text: 'cultural reference', type: 'phrase', context: 'Allusion' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 7,
    title: 'Technology and Innovation',
    description: 'Discuss cutting-edge technology and future developments.',
    content: {
      introduction: 'Communicate about technological advances and innovation.',
      objectives: ['Use technology vocabulary', 'Discuss innovation', 'Understand future trends', 'Discuss implications'],
      mainContent: 'Terms: AI, blockchain, IoT, quantum computing, machine learning, automation, digital transformation.',
      summary: 'You discuss technology and innovation with sophistication.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What does AI primarily refer to?',
        options: ['A type of video', 'Artificial Intelligence', 'An app', 'An artist'],
        correctAnswers: [1],
        explanation: 'AI stands for Artificial Intelligence.',
      },
      {
        type: 'listening',
        question: 'Complete: "Blockchain technology enables _______ transactions."',
        audioPrompt: 'secure',
        options: ['fast', 'secure', 'encrypted', 'protected'],
        correctAnswers: [1],
        explanation: 'Blockchain provides security through decentralization.',
      },
      {
        type: 'multiple-choice',
        question: 'What is IoT?',
        options: ['Internet of Things', 'Input or Table', 'Internet on Television', 'A protocol'],
        correctAnswers: [0],
        explanation: 'IoT connects everyday devices to internet.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "Automation will _______ many industries."',
        options: ['destroy', 'revolutionize', 'ignore', 'skip'],
        correctAnswers: [1],
        explanation: '"Revolutionize" appropriately describes transformative technology.',
      },
      {
        type: 'listening',
        question: 'Complete: "Machine learning algorithms _______ from data patterns."',
        audioPrompt: 'learn',
        options: ['study', 'learn', 'discover', 'identify'],
        correctAnswers: [1],
        explanation: 'Machine learning systems "learn" from training data.',
      },
    ],
    audioContent: [
      { text: 'technology', type: 'word', context: 'Innovation' },
      { text: 'AI', type: 'word', context: 'Artificial Intelligence' },
    ],
  },
  {
    levelId: 7,
    lessonNumber: 8,
    title: 'Global Issues',
    description: 'Discuss international challenges and solutions.',
    content: {
      introduction: 'Engage with worldwide concerns affecting humanity.',
      objectives: ['Discuss international issues', 'Understand complexity', 'Propose solutions', 'Evaluate multiple perspectives'],
      mainContent: 'Topics: migration, poverty, healthcare, education, inequality, geopolitical conflicts, pandemic response.',
      summary: 'You discuss global issues with nuance and understanding.',
    },
    exercises: [
      {
        type: 'multiple-choice',
        question: 'What is a geopolitical issue?',
        options: ['A geographical location', 'A political conflict with geographical importance', 'A climate event', 'A travel problem'],
        correctAnswers: [1],
        explanation: 'Geopolitical issues involve politics and geography.',
      },
      {
        type: 'listening',
        question: 'Complete: "Global _______ requires international cooperation."',
        audioPrompt: 'challenges',
        options: ['problems', 'challenges', 'difficulties', 'issues'],
        correctAnswers: [1],
        explanation: '"Challenges" appropriately describes complex global problems.',
      },
      {
        type: 'multiple-choice',
        question: 'What is sustainable development?',
        options: ['Building buildings', 'Meeting current needs without harming future', 'Economic growth only', 'Technology advancement'],
        correctAnswers: [1],
        explanation: 'Sustainable development balances needs with future impact.',
      },
      {
        type: 'multiple-choice',
        question: 'Complete: "Health inequality _______ millions of people worldwide."',
        options: ['ignores', 'affects', 'helps', 'improves'],
        correctAnswers: [1],
        explanation: '"Affects" describes impact of inequality.',
      },
      {
        type: 'listening',
        question: 'Complete: "Education _______ are critical to breaking cycles of poverty."',
        audioPrompt: 'initiatives',
        options: ['programs', 'initiatives', 'projects', 'plans'],
        correctAnswers: [1],
        explanation: '"Initiatives" appropriately describes coordinated efforts.',
      },
    ],
    audioContent: [
      { text: 'global issues', type: 'phrase', context: 'International concerns' },
      { text: 'sustainable', type: 'word', context: 'Development' },
    ],
  },
];
